const tokenMap = require('./tokens');

const alpha = (color, a) => color + a;

// ── Theme Builder ───────────────────────────────────────────
function buildTheme(name, p) {
  const t = tokenMap(p);

  return {
    name,
    type: 'dark',
    author: 'nathanmillwater',
    colorSpaceName: 'sRGB',

    colors: {
      // ── Contrast Colors ─────────────────────────────────────
      'contrastActiveBorder': p.primaryBright,
      'contrastBorder': p.primaryDim,

      // ── Base Colors ─────────────────────────────────────────
      'descriptionForeground': p.primaryMid,
      'disabledForeground': alpha(p.primaryBright, '26'),
      'errorForeground': p.red,
      'focusBorder': p.red,
      'foreground': p.primaryBright,
      'icon.foreground': p.secondary,
      'sash.hoverBorder': p.primaryDim,
      'selection.background': alpha(p.primary, '26'),
      'widget.border': p.border,
      'widget.shadow': p.black,

      // ── Window Border ───────────────────────────────────────
      'window.activeBorder': p.none,
      'window.inactiveBorder': p.none,

      // ── Text Colors ─────────────────────────────────────────
      'textBlockQuote.background': p.bgLighter,
      'textBlockQuote.border': p.border,
      'textCodeBlock.background': p.bgLighter,
      'textLink.activeForeground': p.primaryBright,
      'textLink.foreground': p.secondaryBright,
      'textPreformat.background': p.bgLighter,
      'textPreformat.border': p.border,
      'textPreformat.foreground': p.primaryBright,
      'textSeparator.foreground': p.primaryDim,

      // ── Action Colors ───────────────────────────────────────
      'toolbar.activeBackground': p.bgLight,
      'toolbar.hoverBackground': p.bgLighter,
      'toolbar.hoverOutline': p.none,

      // ── Button Control ──────────────────────────────────────
      'button.background': p.bgLighter,
      'button.border': p.none,
      'button.foreground': p.primaryBright,
      'button.hoverBackground': p.primaryFaint,
      'button.secondaryBackground': p.bgLighter,
      'button.secondaryBorder': p.none,
      'button.secondaryForeground': p.primary,
      'button.secondaryHoverBackground': p.primaryFaint,
      'button.separator': p.bgLight,
      'checkbox.background': p.bgLighter,
      'checkbox.border': p.borderBright,
      'checkbox.foreground': p.secondaryBright,
      'checkbox.disabled.background': p.bgLighter,
      'checkbox.disabled.foreground': p.primaryGhost,
      'checkbox.selectBackground': p.bgLighter,
      'checkbox.selectBorder': p.borderBright,
      'radio.activeBackground': p.primaryFaint,
      'radio.activeBorder': p.borderBright,
      'radio.activeForeground': p.primaryBright,
      'radio.inactiveBackground': p.bgLighter,
      'radio.inactiveBorder': p.border,
      'radio.inactiveForeground': p.primaryDim,
      'radio.inactiveHoverBackground': p.primaryFaint,

      // ── Dropdown Control ────────────────────────────────────
      'dropdown.background': p.bgLighter,
      'dropdown.border': p.borderBright,
      'dropdown.foreground': p.primaryMid,
      'dropdown.listBackground': p.bgLighter,

      // ── Input Control ───────────────────────────────────────
      'input.background': p.bgLighter,
      'input.border': p.borderBright,
      'input.foreground': p.primaryBright,
      'input.placeholderForeground': p.primaryDim,
      'inputOption.activeBackground': p.primaryFaint,
      'inputOption.activeBorder': p.borderBright,
      'inputOption.activeForeground': p.primaryBright,
      'inputOption.hoverBackground': p.primaryFaint,
      'inputValidation.errorBackground': p.bgLighter,
      'inputValidation.errorBorder': p.red,
      'inputValidation.errorForeground': p.red,
      'inputValidation.infoBackground': p.bgLighter,
      'inputValidation.infoBorder': p.primaryMid,
      'inputValidation.infoForeground': p.primaryMid,
      'inputValidation.warningBackground': p.bgLighter,
      'inputValidation.warningBorder': p.secondary,
      'inputValidation.warningForeground': p.secondary,

      // ── Scrollbar Control ───────────────────────────────────
      'scrollbar.background': p.none,
      'scrollbar.shadow': p.bgLight,
      'scrollbarSlider.activeBackground': alpha(p.primaryBright, '59'),
      'scrollbarSlider.background': alpha(p.primary, '26'),
      'scrollbarSlider.hoverBackground': alpha(p.primaryBright, '26'),

      // ── Badge ───────────────────────────────────────────────
      'badge.background': p.secondaryBright,
      'badge.foreground': p.bgLight,

      // ── Progress Bar ────────────────────────────────────────
      'progressBar.background': p.primaryDim,

      // ── Lists and Trees ─────────────────────────────────────
      'list.activeSelectionBackground': alpha(p.primaryBright, '0c'),
      'list.activeSelectionForeground': p.secondaryBright,
      'list.activeSelectionIconForeground': p.secondaryBright,
      'list.deemphasizedForeground': p.primaryGhost,
      'list.dropBackground': alpha(p.black, 'bf'),
      'list.dropBetweenBackground': p.primaryDim,
      'list.errorForeground': p.red,
      'list.filterMatchBackground': alpha(p.primaryBright, '26'),
      'list.filterMatchBorder': p.none,
      'list.focusAndSelectionOutline': p.primaryDim,
      'list.focusBackground': p.bgLight,
      'list.focusForeground': p.primaryBright,
      'list.focusHighlightForeground': p.primaryBright,
      'list.focusOutline': p.primaryDim,
      'list.highlightForeground': p.primaryBright,
      'list.hoverBackground': alpha(p.primaryBright, '0c'),
      'list.hoverForeground': p.primaryBright,
      'list.inactiveFocusBackground': p.bgLight,
      'list.inactiveFocusOutline': p.none,
      'list.inactiveSelectionBackground': alpha(p.primary, '0c'),
      'list.inactiveSelectionForeground': p.secondaryBright,
      'list.inactiveSelectionIconForeground': p.secondaryBright,
      'list.invalidItemForeground': p.red,
      'list.warningForeground': p.secondary,
      'listFilterWidget.background': p.bgLight,
      'listFilterWidget.noMatchesOutline': p.red,
      'listFilterWidget.outline': p.bgLight,
      'listFilterWidget.shadow': p.black,
      'tree.inactiveIndentGuidesStroke': p.bgLight,
      'tree.indentGuidesStroke': p.bgLighter,
      'tree.tableColumnsBorder': p.border,
      'tree.tableOddRowsBackground': alpha(p.primaryBright, '06'),

      // ── Activity Bar ────────────────────────────────────────
      'activityBar.activeBackground': p.none,
      'activityBar.activeBorder': p.secondaryBright,
      'activityBar.activeFocusBorder': p.secondaryBright,
      'activityBar.background': p.black,
      'activityBar.border': p.border,
      'activityBar.dropBorder': p.primaryDim,
      'activityBar.foreground': p.primary,
      'activityBar.inactiveForeground': p.primaryGhost,
      'activityBarBadge.background': p.secondaryBright,
      'activityBarBadge.foreground': p.bgLight,
      'activityBarTop.activeBackground': p.none,
      'activityBarTop.activeBorder': p.secondaryBright,
      'activityBarTop.background': p.bg,
      'activityBarTop.dropBorder': p.primaryDim,
      'activityBarTop.foreground': p.primary,
      'activityBarTop.inactiveForeground': p.primaryGhost,
      'activityErrorBadge.background': p.red,
      'activityErrorBadge.foreground': p.bgLight,
      'activityWarningBadge.background': p.secondary,
      'activityWarningBadge.foreground': p.bgLight,

      // ── Profiles ────────────────────────────────────────────
      'profileBadge.background': p.bgLighter,
      'profileBadge.foreground': p.primary,
      'profiles.sashBorder': p.border,

      // ── Side Bar ────────────────────────────────────────────
      'sideBar.background': p.bg,
      'sideBar.border': p.border,
      'sideBar.dropBackground': alpha(p.bg, 'bf'),
      'sideBar.foreground': p.primaryMid,
      'sideBarActivityBarTop.border': p.border,
      'sideBarTitle.background': p.bg,
      'sideBarTitle.border': p.border,
      'sideBarSectionHeader.background': p.bg,
      'sideBarSectionHeader.border': p.border,
      'sideBarSectionHeader.foreground': p.primaryDim,
      'sideBarStickyScroll.background': p.bg,
      'sideBarStickyScroll.border': p.border,
      'sideBarStickyScroll.shadow': p.bg,
      'sideBarTitle.foreground': p.primaryGhost,

      // ── Minimap ─────────────────────────────────────────────
      'editorMinimap.inlineChatInserted': alpha(p.secondary, '19'),
      'minimap.background': p.bg,
      'minimap.chatEditHighlight': alpha(p.secondary, '26'),
      'minimap.errorHighlight': alpha(p.red, 'a5'),
      'minimap.findMatchHighlight': alpha(p.primaryMid, 'a5'),
      'minimap.foregroundOpacity': '#000000ff',
      'minimap.infoHighlight': alpha(p.primaryMid, 'a5'),
      'minimap.selectionHighlight': alpha(p.primary, '26'),
      'minimap.selectionOccurrenceHighlight': alpha(p.primaryDim, 'a5'),
      'minimap.warningHighlight': alpha(p.secondary, 'a5'),
      'minimapGutter.addedBackground': p.secondary,
      'minimapGutter.deletedBackground': p.red,
      'minimapGutter.modifiedBackground': p.secondaryBright,
      'minimapSlider.activeBackground': alpha(p.primary, '40'),
      'minimapSlider.background': alpha(p.primary, '19'),
      'minimapSlider.hoverBackground': alpha(p.primary, '26'),

      // ── Editor Groups & Tabs ────────────────────────────────
      'editorGroup.border': p.border,
      'editorGroup.dropBackground': alpha(p.bg, 'bf'),
      'editorGroup.dropIntoPromptBackground': p.bgLighter,
      'editorGroup.dropIntoPromptBorder': p.border,
      'editorGroup.dropIntoPromptForeground': p.primaryBright,
      'editorGroup.emptyBackground': p.black,
      'editorGroup.focusedEmptyBorder': p.border,
      'editorGroupHeader.border': p.none,
      'editorGroupHeader.noTabsBackground': p.bgLight,
      'editorGroupHeader.tabsBackground': p.bgLight,
      'editorGroupHeader.tabsBorder': p.border,
      'editorPane.background': p.bgLight,
      'sideBySideEditor.horizontalBorder': p.border,
      'sideBySideEditor.verticalBorder': p.border,
      'tab.activeBackground': p.bgLight,
      'tab.activeBorder': p.secondaryBright,
      'tab.activeBorderTop': p.none,
      'tab.activeForeground': p.secondaryBright,
      'tab.activeModifiedBorder': p.borderBright,
      'tab.border': p.border,
      'tab.dragAndDropBorder': p.primaryDim,
      'tab.hoverBackground': p.bgLight,
      'tab.hoverBorder': p.borderBright,
      'tab.hoverForeground': p.primaryBright,
      'tab.inactiveBackground': p.bgLight,
      'tab.inactiveForeground': p.primaryMid,
      'tab.inactiveModifiedBorder': p.borderBright,
      'tab.lastPinnedBorder': p.borderBright,
      'tab.selectedBackground': p.bgLight,
      'tab.selectedBorderTop': p.secondaryBright,
      'tab.selectedForeground': p.secondaryBright,
      'tab.unfocusedActiveBorder': p.primaryMid,
      'tab.unfocusedActiveBorderTop': p.none,
      'tab.unfocusedActiveBackground': p.bgLight,
      'tab.unfocusedActiveForeground': p.primary,
      'tab.unfocusedActiveModifiedBorder': p.border,
      'tab.unfocusedHoverBackground': p.bgLight,
      'tab.unfocusedHoverBorder': p.border,
      'tab.unfocusedHoverForeground': p.primary,
      'tab.unfocusedInactiveBackground': p.bgLight,
      'tab.unfocusedInactiveForeground': p.primaryMid,
      'tab.unfocusedInactiveModifiedBorder': p.border,

      // ── Editor Action List ─────────────────────────────────
      'editorActionList.background': p.bgLighter,
      'editorActionList.focusBackground': p.primaryFaint,
      'editorActionList.focusForeground': p.primaryBright,
      'editorActionList.foreground': p.primary,

      // ── Editor ──────────────────────────────────────────────
      'editor.background': p.bg,
      'editor.compositionBorder': p.primaryDim,
      'editor.findMatchBackground': alpha(p.primaryBright, '26'),
      'editor.findMatchBorder': p.secondaryBright,
      'editor.findMatchForeground': p.none,
      'editor.findMatchHighlightBackground': alpha(p.primaryBright, '26'),
      'editor.findMatchHighlightBorder': p.none,
      'editor.findMatchHighlightForeground': p.none,
      'editor.findRangeHighlightBackground': alpha(p.primaryBright, '0c'),
      'editor.findRangeHighlightBorder': p.none,
      'editor.focusedStackFrameHighlightBackground': alpha(p.primary, '26'),
      'editor.foldBackground': alpha(p.primaryBright, '0c'),
      'editor.foldPlaceholderForeground': p.primaryDim,
      'editor.foreground': p.primaryBright,
      'editor.hoverHighlightBackground': alpha(p.primaryBright, '0c'),
      'editor.inactiveLineHighlightBackground': alpha(p.primaryBright, '06'),
      'editor.inactiveSelectionBackground': alpha(p.primaryBright, '0c'),
      'editor.inlineValuesBackground': p.primaryFaint,
      'editor.inlineValuesForeground': p.primary,
      'editor.lineHighlightBackground': alpha(p.primaryBright, '0c'),
      'editor.lineHighlightBorder': p.none,
      'editor.linkedEditingBackground': p.bgLighter,
      'editor.placeholder.foreground': p.primaryDim,
      'editor.rangeHighlightBackground': p.bgLighter,
      'editor.rangeHighlightBorder': p.bgLighter,
      'editor.selectionBackground': alpha(p.primary, '26'),
      'editor.selectionForeground': p.none,
      'editor.selectionHighlightBackground': alpha(p.primaryBright, '26'),
      'editor.selectionHighlightBorder': p.none,
      'editor.snippetFinalTabstopHighlightBackground': alpha(p.secondary, '19'),
      'editor.snippetFinalTabstopHighlightBorder': p.none,
      'editor.snippetTabstopHighlightBackground': alpha(p.primaryBright, '19'),
      'editor.snippetTabstopHighlightBorder': p.none,
      'editor.stackFrameHighlightBackground': alpha(p.primary, '26'),
      'editor.symbolHighlightBackground': alpha(p.primaryBright, '26'),
      'editor.symbolHighlightBorder': p.none,
      'editor.wordHighlightBackground': alpha(p.primaryBright, '26'),
      'editor.wordHighlightBorder': p.none,
      'editor.wordHighlightStrongBackground': alpha(p.primaryBright, '26'),
      'editor.wordHighlightStrongBorder': p.none,
      'editor.wordHighlightTextBackground': alpha(p.primaryBright, '19'),
      'editor.wordHighlightTextBorder': p.none,
      'search.resultsInfoForeground': p.primaryMid,
      'searchEditor.findMatchBackground': alpha(p.primaryBright, '26'),
      'searchEditor.findMatchBorder': p.none,
      'searchEditor.textInputBorder': p.borderBright,

      // ── Editor Line Numbers / Cursor ────────────────────────
      'editorCursor.background': p.bgLight,
      'editorCursor.foreground': p.primaryBright,
      'editorLineNumber.activeForeground': p.primary,
      'editorLineNumber.dimmedForeground': p.primaryGhost,
      'editorLineNumber.foreground': p.primaryGhost,
      'editorMultiCursor.primary.background': p.bgLight,
      'editorMultiCursor.primary.foreground': p.primaryBright,
      'editorMultiCursor.secondary.background': p.bgLight,
      'editorMultiCursor.secondary.foreground': p.primaryMid,

      // ── Editor Unicode Highlight ────────────────────────────
      'editorUnicodeHighlight.background': alpha(p.secondary, '19'),
      'editorUnicodeHighlight.border': p.secondary,

      // ── Editor Link ─────────────────────────────────────────
      'editorLink.activeForeground': p.primaryMid,

      // ── Editor Whitespace / Indent Guides ───────────────────
      'editorWhitespace.foreground': p.primaryGhost,
      'editorIndentGuide.activeBackground': p.primaryDim,
      'editorIndentGuide.activeBackground1': p.primaryDim,
      'editorIndentGuide.activeBackground2': p.primaryDim,
      'editorIndentGuide.activeBackground3': p.primaryDim,
      'editorIndentGuide.activeBackground4': p.primaryDim,
      'editorIndentGuide.activeBackground5': p.primaryDim,
      'editorIndentGuide.activeBackground6': p.primaryDim,
      'editorIndentGuide.background': p.bgLighter,
      'editorIndentGuide.background1': p.bgLighter,
      'editorIndentGuide.background2': p.bgLighter,
      'editorIndentGuide.background3': p.bgLighter,
      'editorIndentGuide.background4': p.bgLighter,
      'editorIndentGuide.background5': p.bgLighter,
      'editorIndentGuide.background6': p.bgLighter,

      // ── Editor Inlay Hints ──────────────────────────────────
      'editorInlayHint.background': p.bgLighter,
      'editorInlayHint.foreground': p.primaryMid,
      'editorInlayHint.parameterBackground': p.bgLighter,
      'editorInlayHint.parameterForeground': p.primaryDim,
      'editorInlayHint.typeBackground': p.bgLighter,
      'editorInlayHint.typeForeground': p.primaryDim,

      // ── Editor Ruler ────────────────────────────────────────
      'editorRuler.foreground': p.primaryGhost,

      // ── Editor Code Lens ────────────────────────────────────
      'editorCodeLens.foreground': p.primaryDim,

      // ── Editor Light Bulb ───────────────────────────────────
      'editorLightBulb.foreground': p.secondaryBright,
      'editorLightBulbAi.foreground': p.secondaryBright,
      'editorLightBulbAutoFix.foreground': p.secondary,

      // ── Editor Bracket Matching ─────────────────────────────
      'editorBracketMatch.background': p.bgLight,
      'editorBracketMatch.border': p.primaryDim,
      'editorBracketMatch.foreground': p.primaryBright,

      // ── Editor Bracket Highlighting ─────────────────────────
      'editorBracketHighlight.foreground1': p.red,
      'editorBracketHighlight.foreground2': p.secondary,
      'editorBracketHighlight.foreground3': p.secondaryBright,
      'editorBracketHighlight.foreground4': p.primary,
      'editorBracketHighlight.foreground5': p.primaryMid,
      'editorBracketHighlight.foreground6': p.secondaryDim,
      'editorBracketHighlight.unexpectedBracket.foreground': p.red,

      // ── Editor Bracket Pair Guides ──────────────────────────
      'editorBracketPairGuide.activeBackground1': p.red,
      'editorBracketPairGuide.activeBackground2': p.secondary,
      'editorBracketPairGuide.activeBackground3': p.secondaryBright,
      'editorBracketPairGuide.activeBackground4': p.primary,
      'editorBracketPairGuide.activeBackground5': p.primaryMid,
      'editorBracketPairGuide.activeBackground6': p.secondaryDim,
      'editorBracketPairGuide.background1': alpha(p.red, '59'),
      'editorBracketPairGuide.background2': alpha(p.secondary, '59'),
      'editorBracketPairGuide.background3': alpha(p.secondaryBright, '59'),
      'editorBracketPairGuide.background4': alpha(p.primary, '59'),
      'editorBracketPairGuide.background5': alpha(p.primaryMid, '59'),
      'editorBracketPairGuide.background6': alpha(p.secondaryDim, '59'),

      // ── Editor Overview Ruler ───────────────────────────────
      'editorOverviewRuler.addedForeground': p.secondary,
      'editorOverviewRuler.background': p.none,
      'editorOverviewRuler.border': p.border,
      'editorOverviewRuler.bracketMatchForeground': p.primaryDim,
      'editorOverviewRuler.commentDraftForeground': p.primaryDim,
      'editorOverviewRuler.commentForeground': p.primaryMid,
      'editorOverviewRuler.commentUnresolvedForeground': p.secondary,
      'editorOverviewRuler.commonContentForeground': p.bgLighter,
      'editorOverviewRuler.currentContentForeground': p.bgLighter,
      'editorOverviewRuler.deletedForeground': p.red,
      'editorOverviewRuler.errorForeground': p.red,
      'editorOverviewRuler.findMatchForeground': alpha(p.primaryBright, '26'),
      'editorOverviewRuler.incomingContentForeground': p.bgLighter,
      'editorOverviewRuler.infoForeground': p.primaryMid,
      'editorOverviewRuler.inlineChatInserted': alpha(p.secondary, '40'),
      'editorOverviewRuler.inlineChatRemoved': alpha(p.red, '40'),
      'editorOverviewRuler.modifiedForeground': p.secondary,
      'editorOverviewRuler.rangeHighlightForeground': alpha(p.primaryBright, '26'),
      'editorOverviewRuler.selectionHighlightForeground': alpha(p.primaryBright, '26'),
      'editorOverviewRuler.warningForeground': p.secondary,
      'editorOverviewRuler.wordHighlightForeground': alpha(p.primaryBright, '26'),
      'editorOverviewRuler.wordHighlightStrongForeground': alpha(p.primaryBright, '26'),
      'editorOverviewRuler.wordHighlightTextForeground': alpha(p.primaryBright, '26'),

      // ── Editor Errors / Warnings / Info / Hints ─────────────
      'editorError.background': p.none,
      'editorError.border': p.none,
      'editorError.foreground': p.red,
      'editorWarning.background': p.none,
      'editorWarning.border': p.none,
      'editorWarning.foreground': p.secondary,
      'editorInfo.background': p.none,
      'editorInfo.border': p.border,
      'editorInfo.foreground': p.primaryMid,
      'editorHint.border': p.border,
      'editorHint.foreground': p.secondaryDim,
      'problemsErrorIcon.foreground': p.red,
      'problemsInfoIcon.foreground': p.primaryMid,
      'problemsWarningIcon.foreground': p.secondary,

      // ── Editor Unnecessary Code ─────────────────────────────
      'editorUnnecessaryCode.border': p.none,
      'editorUnnecessaryCode.opacity': '#000000a5',

      // ── Editor Ghost Text ───────────────────────────────────
      'editorGhostText.background': p.none,
      'editorGhostText.border': p.none,
      'editorGhostText.foreground': p.primaryDim,

      // ── Editor Gutter ───────────────────────────────────────
      'editorGutter.addedBackground': p.secondary,
      'editorGutter.background': p.bgLight,
      'editorGutter.addedSecondaryBackground': alpha(p.secondary, '40'),
      'editorGutter.commentDraftGlyphForeground': p.primaryDim,
      'editorGutter.commentGlyphForeground': p.primaryMid,
      'editorGutter.commentRangeForeground': p.primaryDim,
      'editorGutter.commentUnresolvedGlyphForeground': p.secondary,
      'editorGutter.deletedBackground': p.red,
      'editorGutter.deletedSecondaryBackground': alpha(p.red, '40'),
      'editorGutter.foldingControlForeground': p.primary,
      'editorGutter.itemBackground': p.none,
      'editorGutter.itemGlyphForeground': p.primaryMid,
      'editorGutter.modifiedBackground': p.secondary,
      'editorGutter.modifiedSecondaryBackground': alpha(p.secondary, '40'),

      // ── Editor Comments Widget ──────────────────────────────
      'editorCommentsWidget.rangeActiveBackground': alpha(p.primaryBright, '19'),
      'editorCommentsWidget.rangeBackground': alpha(p.primaryBright, '0c'),
      'editorCommentsWidget.replyInputBackground': p.bgLighter,
      'editorCommentsWidget.resolvedBorder': p.primaryDim,
      'editorCommentsWidget.unresolvedBorder': p.secondary,

      // ── Editor Sticky Scroll ────────────────────────────────
      'editorStickyScroll.background': p.bgLight,
      'editorStickyScroll.border': p.border,
      'editorStickyScroll.shadow': p.bgLight,
      'editorStickyScrollGutter.background': p.bgLight,
      'editorStickyScrollHover.background': alpha(p.primaryBright, '0c'),

      // ── Editor Hover Widget ─────────────────────────────────
      'editorHoverWidget.background': p.bgLighter,
      'editorHoverWidget.border': p.border,
      'editorHoverWidget.foreground': p.primary,
      'editorHoverWidget.highlightForeground': p.primaryBright,
      'editorHoverWidget.statusBarBackground': p.bgLight,

      // ── Editor Suggest Widget ───────────────────────────────
      'editorSuggestWidget.background': p.bgLighter,
      'editorSuggestWidget.border': p.border,
      'editorSuggestWidget.focusHighlightForeground': p.secondaryBright,
      'editorSuggestWidget.foreground': p.primary,
      'editorSuggestWidget.highlightForeground': p.primaryBright,
      'editorSuggestWidget.selectedBackground': p.primaryFaint,
      'editorSuggestWidget.selectedForeground': p.primaryBright,
      'editorSuggestWidget.selectedIconForeground': p.secondaryBright,
      'editorSuggestWidgetStatus.foreground': p.primaryDim,

      // ── Editor Widget ───────────────────────────────────────
      'editorWidget.background': p.bgLighter,
      'editorWidget.border': p.border,
      'editorWidget.foreground': p.primary,
      'editorWidget.resizeBorder': p.primaryDim,

      // ── Editor Marker Navigation ────────────────────────────
      'editorMarkerNavigation.background': p.bgLighter,
      'editorMarkerNavigationError.background': p.red,
      'editorMarkerNavigationError.headerBackground': alpha(p.red, '19'),
      'editorMarkerNavigationInfo.background': p.primaryMid,
      'editorMarkerNavigationInfo.headerBackground': alpha(p.primaryMid, '19'),
      'editorMarkerNavigationWarning.background': p.secondary,
      'editorMarkerNavigationWarning.headerBackground': alpha(p.secondary, '19'),

      // ── Inline Edit ─────────────────────────────────────────
      'inlineEdit.gutterIndicator.background': p.bgLighter,
      'inlineEdit.gutterIndicator.primaryBackground': p.primaryFaint,
      'inlineEdit.gutterIndicator.primaryBorder': p.primaryDim,
      'inlineEdit.gutterIndicator.primaryForeground': p.primaryBright,
      'inlineEdit.gutterIndicator.secondaryBackground': p.bgLighter,
      'inlineEdit.gutterIndicator.secondaryBorder': p.borderBright,
      'inlineEdit.gutterIndicator.secondaryForeground': p.primaryMid,
      'inlineEdit.gutterIndicator.successfulBackground': alpha(p.secondary, '26'),
      'inlineEdit.gutterIndicator.successfulBorder': p.secondary,
      'inlineEdit.gutterIndicator.successfulForeground': p.secondary,
      'inlineEdit.modifiedBackground': alpha(p.secondary, '19'),
      'inlineEdit.modifiedBorder': p.secondary,
      'inlineEdit.modifiedChangedLineBackground': alpha(p.secondary, '19'),
      'inlineEdit.modifiedChangedTextBackground': alpha(p.secondary, '26'),
      'inlineEdit.originalBackground': alpha(p.red, '19'),
      'inlineEdit.originalBorder': p.red,
      'inlineEdit.originalChangedLineBackground': alpha(p.red, '19'),
      'inlineEdit.originalChangedTextBackground': alpha(p.red, '26'),
      'inlineEdit.tabWillAcceptModifiedBorder': p.secondary,
      'inlineEdit.tabWillAcceptOriginalBorder': p.red,

      // ── Diff Editor ─────────────────────────────────────────
      'diffEditor.border': p.border,
      'diffEditor.diagonalFill': p.bgLighter,
      'diffEditor.insertedLineBackground': alpha(p.secondary, '19'),
      'diffEditor.insertedTextBackground': alpha(p.secondary, '19'),
      'diffEditor.insertedTextBorder': p.none,
      'diffEditor.move.border': '',
      'diffEditor.moveActive.border': '',
      'diffEditor.removedLineBackground': alpha(p.red, '19'),
      'diffEditor.removedTextBackground': alpha(p.red, '19'),
      'diffEditor.removedTextBorder': p.none,
      'diffEditor.unchangedCodeBackground': p.bg,
      'diffEditor.unchangedRegionBackground': p.bg,
      'diffEditor.unchangedRegionForeground': p.primary,
      'diffEditor.unchangedRegionShadow': p.black,
      'diffEditorGutter.insertedLineBackground': alpha(p.secondary, '19'),
      'diffEditorGutter.removedLineBackground': alpha(p.red, '19'),
      'diffEditorOverview.insertedForeground': alpha(p.secondary, 'a5'),
      'diffEditorOverview.removedForeground': alpha(p.red, 'a5'),
      'multiDiffEditor.background': p.bg,
      'multiDiffEditor.border': p.border,
      'multiDiffEditor.headerBackground': p.bgLight,

      // ── Chat ────────────────────────────────────────────────
      'chat.avatarBackground': p.bgLight,
      'chat.avatarForeground': p.secondaryDim,
      'chat.checkpointSeparator': p.border,
      'chat.editedFileForeground': p.secondaryBright,
      'chat.linesAddedForeground': p.secondary,
      'chat.linesRemovedForeground': p.red,
      'chat.requestBackground': p.bgLighter,
      'chat.requestBorder': p.borderBright,
      'chat.requestBubbleBackground': p.bgLighter,
      'chat.requestBubbleHoverBackground': p.primaryFaint,
      'chat.requestCodeBorder': p.border,
      'chat.slashCommandBackground': p.none,
      'chat.slashCommandForeground': p.secondaryBright,
      'chat.thinkingShimmer': p.primaryDim,
      'chatManagement.sashBorder': p.border,

      // ── Inline Chat ─────────────────────────────────────────
      'inlineChat.background': p.bgLight,
      'inlineChat.border': p.border,
      'inlineChat.foreground': p.primaryBright,
      'inlineChat.shadow': p.black,
      'inlineChatDiff.inserted': alpha(p.secondary, '19'),
      'inlineChatDiff.removed': alpha(p.red, '19'),
      'inlineChatInput.background': p.bgLighter,
      'inlineChatInput.border': p.borderBright,
      'inlineChatInput.focusBorder': p.primaryDim,
      'inlineChatInput.placeholderForeground': p.primaryDim,

      // ── Interactive ─────────────────────────────────────────
      'interactive.activeCodeBorder': p.primaryDim,
      'interactive.inactiveCodeBorder': p.border,

      // ── Peek View ───────────────────────────────────────────
      'peekView.border': p.border,
      'peekViewEditor.background': p.bgLighter,
      'peekViewEditor.matchHighlightBackground': p.primaryFaint,
      'peekViewEditor.matchHighlightBorder': p.none,
      'peekViewEditorGutter.background': p.bgLighter,
      'peekViewEditorStickyScroll.background': p.bgLighter,
      'peekViewEditorStickyScrollGutter.background': p.bgLighter,
      'peekViewResult.background': p.bgLighter,
      'peekViewResult.fileForeground': p.primaryMid,
      'peekViewResult.lineForeground': p.primaryMid,
      'peekViewResult.matchHighlightBackground': p.primaryFaint,
      'peekViewResult.selectionBackground': p.bgLighter,
      'peekViewResult.selectionForeground': p.primaryBright,
      'peekViewTitle.background': p.bg,
      'peekViewTitleDescription.foreground': p.primaryMid,
      'peekViewTitleLabel.foreground': p.primaryBright,

      // ── Merge Conflicts ─────────────────────────────────────
      'merge.border': p.border,
      'merge.commonContentBackground': alpha(p.primaryBright, '19'),
      'merge.commonHeaderBackground': alpha(p.primaryBright, '26'),
      'merge.currentContentBackground': alpha(p.red, '19'),
      'merge.currentHeaderBackground': alpha(p.red, '26'),
      'merge.incomingContentBackground': alpha(p.secondary, '19'),
      'merge.incomingHeaderBackground': alpha(p.secondary, '26'),
      'mergeEditor.change.background': alpha(p.primaryBright, '19'),
      'mergeEditor.change.word.background': alpha(p.primaryBright, '19'),
      'mergeEditor.changeBase.background': alpha(p.primaryBright, '19'),
      'mergeEditor.changeBase.word.background': alpha(p.primaryBright, '26'),
      'mergeEditor.conflict.handled.minimapOverViewRuler': p.secondary,
      'mergeEditor.conflict.handledFocused.border': p.secondary,
      'mergeEditor.conflict.handledUnfocused.border': p.secondary,
      'mergeEditor.conflict.input1.background': alpha(p.red, '19'),
      'mergeEditor.conflict.input2.background': alpha(p.secondary, '19'),
      'mergeEditor.conflict.unhandled.minimapOverViewRuler': p.red,
      'mergeEditor.conflict.unhandledFocused.border': p.red,
      'mergeEditor.conflict.unhandledUnfocused.border': p.red,
      'mergeEditor.conflictingLines.background': alpha(p.primaryBright, '19'),

      // ── Panel ───────────────────────────────────────────────
      'outputView.background': p.bgLighter,
      'outputViewStickyScroll.background': p.bgLighter,
      'panel.background': p.bgLighter,
      'panel.border': p.border,
      'panel.dropBorder': p.primaryDim,
      'panel.dropBackground': alpha(p.bg, 'bf'),
      'panelInput.border': p.borderBright,
      'panelSection.border': p.border,
      'panelSection.dropBackground': alpha(p.bg, 'bf'),
      'panelSectionHeader.background': p.bgLighter,
      'panelSectionHeader.border': p.border,
      'panelSectionHeader.foreground': p.primaryMid,
      'panelTitle.border': p.none,
      'panelTitleBadge.background': p.secondaryBright,
      'panelTitleBadge.foreground': p.bgLight,
      'panelStickyScroll.background': p.bgLighter,
      'panelStickyScroll.border': p.borderBright,
      'panelStickyScroll.shadow': p.bgLighter,
      'panelTitle.activeBorder': p.secondaryBright,
      'panelTitle.activeForeground': p.secondaryBright,
      'panelTitle.inactiveForeground': p.primaryMid,

      // ── Status Bar ──────────────────────────────────────────
      'statusBar.background': p.primaryFaint,
      'statusBar.border': p.border,
      'statusBar.debuggingBackground': p.primaryDim,
      'statusBar.debuggingBorder': p.border,
      'statusBar.debuggingForeground': p.primaryBright,
      'statusBar.focusBorder': p.border,
      'statusBar.foreground': p.primaryDim,
      'statusBar.noFolderBackground': p.bg,
      'statusBar.noFolderBorder': p.border,
      'statusBar.noFolderForeground': p.primaryDim,
      'statusBarItem.activeBackground': p.bgLight,
      'statusBarItem.compactHoverBackground': p.bgLight,
      'statusBarItem.errorBackground': p.bgLight,
      'statusBarItem.errorForeground': p.red,
      'statusBarItem.errorHoverBackground': p.bgLighter,
      'statusBarItem.errorHoverForeground': p.red,
      'statusBarItem.focusBorder': p.primaryDim,
      'statusBarItem.hoverBackground': p.bg,
      'statusBarItem.hoverForeground': p.primaryBright,
      'statusBarItem.offlineBackground': '',
      'statusBarItem.offlineForeground': '',
      'statusBarItem.offlineHoverBackground': p.bgLighter,
      'statusBarItem.offlineHoverForeground': p.primaryDim,
      'statusBarItem.prominentBackground': p.bgLighter,
      'statusBarItem.prominentForeground': p.primaryBright,
      'statusBarItem.prominentHoverBackground': p.bgLighter,
      'statusBarItem.prominentHoverForeground': p.primaryBright,
      'statusBarItem.remoteBackground': p.bg,
      'statusBarItem.remoteForeground': p.secondary,
      'statusBarItem.remoteHoverBackground': p.secondary,
      'statusBarItem.remoteHoverForeground': p.bgLight,
      'statusBarItem.warningBackground': p.bgLight,
      'statusBarItem.warningForeground': p.secondary,
      'statusBarItem.warningHoverBackground': p.bgLighter,
      'statusBarItem.warningHoverForeground': p.secondary,

      // ── Title Bar ───────────────────────────────────────────
      'titleBar.activeBackground': p.primaryDim,
      'titleBar.activeForeground': p.primaryWhite,
      'titleBar.border': p.border,
      'titleBar.inactiveBackground': p.bg,
      'titleBar.inactiveForeground': p.primaryGhost,

      // ── Menu Bar ────────────────────────────────────────────
      'menu.background': p.bgLight,
      'menu.border': p.border,
      'menu.foreground': p.primaryBright,
      'menu.selectionBackground': p.bgLighter,
      'menu.selectionBorder': p.none,
      'menu.selectionForeground': p.secondaryBright,
      'menu.separatorBackground': p.bgLighter,
      'menubar.selectionBackground': p.bgLighter,
      'menubar.selectionBorder': p.none,
      'menubar.selectionForeground': p.primaryBright,

      // ── Command Center ──────────────────────────────────────
      'commandCenter.activeBackground': p.bgLight,
      'commandCenter.activeBorder': p.primaryDim,
      'commandCenter.activeForeground': p.primary,
      'commandCenter.background': p.bg,
      'commandCenter.border': p.border,
      'commandCenter.debuggingBackground': p.bg,
      'commandCenter.foreground': p.primaryMid,
      'commandCenter.inactiveBorder': p.border,
      'commandCenter.inactiveForeground': p.primaryDim,

      // ── Notifications ───────────────────────────────────────
      'notificationCenter.border': p.border,
      'notificationCenterHeader.background': p.bgLighter,
      'notificationCenterHeader.foreground': p.primaryMid,
      'notificationLink.foreground': p.secondaryBright,
      'notificationToast.border': p.border,
      'notifications.background': p.bgLighter,
      'notifications.border': p.border,
      'notifications.foreground': p.primary,
      'notificationsErrorIcon.foreground': p.red,
      'notificationsInfoIcon.foreground': p.primaryMid,
      'notificationsWarningIcon.foreground': p.secondary,

      // ── Banner ──────────────────────────────────────────────
      'banner.background': p.bgLighter,
      'banner.foreground': p.primary,
      'banner.iconForeground': p.primary,

      // ── Extensions ──────────────────────────────────────────
      'extensionBadge.remoteBackground': p.secondary,
      'extensionBadge.remoteForeground': p.primaryBright,
      'extensionButton.background': p.bgLighter,
      'extensionButton.border': p.none,
      'extensionButton.foreground': p.primary,
      'extensionButton.hoverBackground': p.primaryFaint,
      'extensionButton.prominentBackground': p.bgLighter,
      'extensionButton.prominentForeground': p.primaryBright,
      'extensionButton.prominentHoverBackground': p.primaryFaint,
      'extensionButton.separator': p.bgLight,
      'extensionIcon.preReleaseForeground': p.secondaryDim,
      'extensionIcon.sponsorForeground': p.primaryMid,
      'extensionIcon.privateForeground': p.primaryDim,
      'extensionIcon.starForeground': p.secondaryBright,
      'extensionIcon.verifiedForeground': p.secondary,
      'mcpIcon.starForeground': p.secondaryBright,

      // ── Quick Picker ────────────────────────────────────────
      'pickerGroup.border': p.border,
      'pickerGroup.foreground': p.primaryGhost,
      'quickInput.background': p.bgLighter,
      'quickInput.foreground': p.primaryMid,
      'quickInputList.focusBackground': p.primaryFaint,
      'quickInputList.focusForeground': p.primaryBright,
      'quickInputList.focusIconForeground': p.secondaryBright,
      'quickInputTitle.background': p.bgLighter,

      // ── Keybinding Label ────────────────────────────────────
      'keybindingLabel.background': p.primaryFaint,
      'keybindingLabel.border': p.borderBright,
      'keybindingLabel.bottomBorder': p.borderBright,
      'keybindingLabel.foreground': p.primary,
      'keybindingTable.headerBackground': p.bgLighter,
      'keybindingTable.rowsBackground': p.bgLight,

      // ── Terminal ────────────────────────────────────────────
      'terminal.ansiBlack': p.bgLighter,
      'terminal.ansiBlue': p.primaryMid,
      'terminal.ansiBrightBlack': p.primaryDim,
      'terminal.ansiBrightBlue': p.primary,
      'terminal.ansiBrightCyan': p.primaryWhite,
      'terminal.ansiBrightGreen': p.secondaryBright,
      'terminal.ansiBrightMagenta': p.secondaryDim,
      'terminal.ansiBrightRed': p.redBright,
      'terminal.ansiBrightWhite': p.primaryBright,
      'terminal.ansiBrightYellow': p.secondaryBright,
      'terminal.ansiCyan': p.primaryMid,
      'terminal.ansiGreen': p.secondary,
      'terminal.ansiMagenta': p.secondaryDim,
      'terminal.ansiRed': p.red,
      'terminal.ansiWhite': p.primaryBright,
      'terminal.ansiYellow': p.secondary,
      'terminal.background': p.bgLighter,
      'terminal.border': p.border,
      'terminal.dropBackground': alpha(p.bg, 'bf'),
      'terminal.findMatchBackground': alpha(p.primaryBright, '26'),
      'terminal.findMatchBorder': p.secondaryBright,
      'terminal.findMatchHighlightBackground': alpha(p.primaryBright, '19'),
      'terminal.findMatchHighlightBorder': p.none,
      'terminal.foreground': p.primaryBright,
      'terminal.hoverHighlightBackground': alpha(p.primaryBright, '0c'),
      'terminal.inactiveSelectionBackground': alpha(p.primaryBright, '19'),
      'terminal.initialHintForeground': p.primaryDim,
      'terminal.selectionBackground': alpha(p.primaryBright, '26'),
      'terminal.selectionForeground': p.none,
      'terminal.tab.activeBorder': p.secondaryBright,
      'terminalCommandDecoration.defaultBackground': p.primaryBright,
      'terminalCommandDecoration.errorBackground': p.red,
      'terminalCommandDecoration.successBackground': p.secondary,
      'terminalCommandGuide.foreground': p.primaryDim,
      'terminalCursor.background': p.none,
      'terminalCursor.foreground': p.primaryBright,
      'terminalOverviewRuler.border': p.border,
      'terminalOverviewRuler.cursorForeground': p.primaryBright,
      'terminalOverviewRuler.findMatchForeground': p.secondaryBright,
      'terminalStickyScroll.background': p.bgLighter,
      'terminalStickyScroll.border': p.border,
      'terminalStickyScrollHover.background': alpha(p.primaryBright, '0c'),
      'terminalSymbolIcon.aliasForeground': p.secondary,
      'terminalSymbolIcon.argumentForeground': p.primaryMid,
      'terminalSymbolIcon.branchForeground': p.secondary,
      'terminalSymbolIcon.commitForeground': p.secondaryBright,
      'terminalSymbolIcon.fileForeground': p.primary,
      'terminalSymbolIcon.flagForeground': p.primaryMid,
      'terminalSymbolIcon.folderForeground': p.primary,
      'terminalSymbolIcon.inlineSuggestionForeground': p.primaryDim,
      'terminalSymbolIcon.methodForeground': p.secondary,
      'terminalSymbolIcon.optionForeground': p.primaryMid,
      'terminalSymbolIcon.optionValueForeground': p.primaryBright,
      'terminalSymbolIcon.pullRequestDoneForeground': p.secondary,
      'terminalSymbolIcon.pullRequestForeground': p.secondaryBright,
      'terminalSymbolIcon.remoteForeground': p.secondary,
      'terminalSymbolIcon.stashForeground': p.secondaryDim,
      'terminalSymbolIcon.symbolText': p.primaryBright,
      'terminalSymbolIcon.symbolicLinkFileForeground': p.primaryMid,
      'terminalSymbolIcon.symbolicLinkFolderForeground': p.primaryMid,
      'terminalSymbolIcon.tagForeground': p.secondaryDim,

      // ── Debug Toolbar / View ────────────────────────────────
      'debugToolBar.background': p.bgLighter,
      'debugToolBar.border': p.border,
      'debugView.exceptionLabelBackground': p.red,
      'debugView.exceptionLabelForeground': p.bgLight,
      'debugView.stateLabelBackground': p.secondary,
      'debugView.stateLabelForeground': p.bgLight,
      'debugView.valueChangedHighlight': p.secondaryBright,

      // ── Debug Console ───────────────────────────────────────
      'debugConsole.errorForeground': p.red,
      'debugConsole.infoForeground': p.primaryMid,
      'debugConsole.sourceForeground': p.primaryBright,
      'debugConsole.warningForeground': p.secondary,
      'debugConsoleInputIcon.foreground': p.secondaryBright,

      // ── Debug Exception Widget ──────────────────────────────
      'debugExceptionWidget.background': p.bgLighter,
      'debugExceptionWidget.border': p.border,

      // ── Debug Token Expression ──────────────────────────────
      'debugTokenExpression.boolean': p.secondary,
      'debugTokenExpression.error': p.red,
      'debugTokenExpression.name': p.primaryMid,
      'debugTokenExpression.number': p.secondaryDim,
      'debugTokenExpression.string': p.secondaryBright,
      'debugTokenExpression.type': p.primaryMid,
      'debugTokenExpression.value': p.primaryBright,

      // ── Debug Icons ─────────────────────────────────────────
      'debugIcon.breakpointCurrentStackframeForeground': p.secondaryBright,
      'debugIcon.breakpointDisabledForeground': p.primary,
      'debugIcon.breakpointForeground': p.red,
      'debugIcon.breakpointStackframeForeground': p.primaryBright,
      'debugIcon.breakpointUnverifiedForeground': p.secondary,
      'debugIcon.continueForeground': p.primaryBright,
      'debugIcon.disconnectForeground': p.primaryBright,
      'debugIcon.pauseForeground': p.primaryBright,
      'debugIcon.restartForeground': p.secondary,
      'debugIcon.startForeground': p.secondary,
      'debugIcon.stepBackForeground': p.primaryBright,
      'debugIcon.stepIntoForeground': p.primaryBright,
      'debugIcon.stepOutForeground': p.primaryBright,
      'debugIcon.stepOverForeground': p.primaryBright,
      'debugIcon.stopForeground': p.red,

      // ── Testing ─────────────────────────────────────────────
      'testing.coverCountBadgeBackground': p.bgLighter,
      'testing.coverCountBadgeForeground': p.primaryBright,
      'testing.coveredBackground': alpha(p.secondary, '19'),
      'testing.coveredBorder': p.none,
      'testing.coveredGutterBackground': alpha(p.secondary, '26'),
      'testing.iconErrored': p.red,
      'testing.iconErrored.retired': alpha(p.red, '59'),
      'testing.iconFailed': p.red,
      'testing.iconFailed.retired': alpha(p.red, '59'),
      'testing.iconPassed': p.secondary,
      'testing.iconPassed.retired': alpha(p.secondary, '59'),
      'testing.iconQueued': p.primaryBright,
      'testing.iconQueued.retired': alpha(p.primaryBright, '59'),
      'testing.iconSkipped': p.secondary,
      'testing.iconSkipped.retired': alpha(p.secondary, '59'),
      'testing.iconUnset': p.primaryMid,
      'testing.iconUnset.retired': alpha(p.primaryMid, '59'),
      'testing.message.error.badgeBackground': p.red,
      'testing.message.error.badgeBorder': p.red,
      'testing.message.error.badgeForeground': p.bgLight,
      'testing.message.error.decorationForeground': p.red,
      'testing.message.error.lineBackground': alpha(p.red, '19'),
      'testing.message.info.decorationForeground': p.primaryBright,
      'testing.message.info.lineBackground': alpha(p.primaryBright, '19'),
      'testing.messagePeekBorder': p.border,
      'testing.messagePeekHeaderBackground': p.bgLighter,
      'testing.peekBorder': p.border,
      'testing.peekHeaderBackground': p.bgLighter,
      'testing.runAction': p.secondaryBright,
      'testing.uncoveredBackground': alpha(p.red, '19'),
      'testing.uncoveredBorder': p.none,
      'testing.uncoveredBranchBackground': alpha(p.red, '19'),
      'testing.uncoveredGutterBackground': alpha(p.red, '26'),

      // ── Welcome Page ────────────────────────────────────────
      'walkThrough.embeddedEditorBackground': p.bg,
      'walkthrough.stepTitle.foreground': p.primaryBright,
      'welcomePage.background': p.bg,
      'welcomePage.buttonBackground': p.bgLighter,
      'welcomePage.buttonHoverBackground': p.primaryFaint,
      'welcomePage.progress.background': p.primaryDim,
      'welcomePage.progress.foreground': p.primaryMid,
      'welcomePage.tileBackground': p.bgLighter,
      'welcomePage.tileBorder': p.border,
      'welcomePage.tileHoverBackground': p.primaryFaint,
      'welcomePage.tileShadow': p.black,

      // ── Git Decorations ─────────────────────────────────────
      'git.blame.editorDecorationForeground': p.primaryGhost,
      'gitDecoration.addedResourceForeground': p.secondary,
      'gitDecoration.conflictingResourceForeground': p.secondary,
      'gitDecoration.deletedResourceForeground': p.red,
      'gitDecoration.ignoredResourceForeground': p.primaryGhost,
      'gitDecoration.modifiedResourceForeground': p.secondaryBright,
      'gitDecoration.renamedResourceForeground': p.primaryMid,
      'gitDecoration.stageDeletedResourceForeground': p.red,
      'gitDecoration.stageModifiedResourceForeground': p.secondaryBright,
      'gitDecoration.submoduleResourceForeground': p.primaryDim,
      'gitDecoration.untrackedResourceForeground': p.primary,

      // ── SCM Graph ───────────────────────────────────────────
      'scmGraph.foreground1': p.red,
      'scmGraph.foreground2': p.secondary,
      'scmGraph.foreground3': p.secondaryBright,
      'scmGraph.foreground4': p.primary,
      'scmGraph.foreground5': p.secondaryDim,
      'scmGraph.historyItemBaseRefColor': p.primaryMid,
      'scmGraph.historyItemHoverAdditionsForeground': p.secondary,
      'scmGraph.historyItemHoverDefaultLabelBackground': p.primaryDim,
      'scmGraph.historyItemHoverDefaultLabelForeground': p.bgLight,
      'scmGraph.historyItemHoverDeletionsForeground': p.red,
      'scmGraph.historyItemHoverLabelForeground': p.bgLight,
      'scmGraph.historyItemRefColor': p.secondaryDim,
      'scmGraph.historyItemRemoteRefColor': p.secondary,

      // ── Breadcrumb ──────────────────────────────────────────
      'breadcrumb.activeSelectionForeground': p.primaryBright,
      'breadcrumb.background': p.bg,
      'breadcrumb.focusForeground': p.primary,
      'breadcrumb.foreground': p.primaryMid,
      'breadcrumbPicker.background': p.bgLight,

      // ── Charts ──────────────────────────────────────────────
      'charts.blue': p.primaryMid,
      'charts.foreground': p.primaryBright,
      'charts.green': p.secondary,
      'charts.lines': p.primaryDim,
      'charts.orange': p.secondary,
      'charts.purple': p.secondaryDim,
      'charts.red': p.red,
      'charts.yellow': p.secondaryBright,

      // ── Ports ───────────────────────────────────────────────
      'ports.iconRunningProcessForeground': p.secondary,

      // ── Settings ────────────────────────────────────────────
      'settings.checkboxBackground': p.bgLighter,
      'settings.checkboxBorder': p.borderBright,
      'settings.checkboxForeground': p.secondaryBright,
      'settings.dropdownBackground': p.bgLighter,
      'settings.dropdownBorder': p.borderBright,
      'settings.dropdownForeground': p.primaryBright,
      'settings.dropdownListBorder': p.primaryMid,
      'settings.focusedRowBackground': alpha(p.primaryBright, '0c'),
      'settings.focusedRowBorder': p.primaryDim,
      'settings.headerForeground': p.secondaryBright,
      'settings.modifiedItemForeground': p.secondaryBright,
      'settings.modifiedItemIndicator': p.secondaryBright,
      'settings.numberInputBackground': p.bgLighter,
      'settings.numberInputBorder': p.borderBright,
      'settings.numberInputForeground': p.primaryBright,
      'settings.rowHoverBackground': alpha(p.primaryDim, '0c'),
      'settings.sashBorder': p.border,
      'settings.settingsHeaderHoverForeground': p.primaryBright,
      'settings.textInputBackground': p.bgLighter,
      'settings.textInputBorder': p.borderBright,
      'settings.textInputForeground': p.primaryBright,

      // ── Notebook ────────────────────────────────────────────
      'notebook.cellBorderColor': p.border,
      'notebook.cellEditorBackground': alpha(p.bg, '7f'),
      'notebook.cellInsertionIndicator': p.primaryBright,
      'notebook.cellStatusBarItemHoverBackground': p.primaryDim,
      'notebook.cellToolbarSeparator': p.bgLighter,
      'notebook.editorBackground': p.bgLight,
      'notebook.focusedEditorBorder': p.primaryDim,
      'notebookStatusErrorIcon.foreground': p.red,
      'notebookStatusRunningIcon.foreground': p.primaryBright,
      'notebookStatusSuccessIcon.foreground': p.secondary,

      // ── Symbol Icons ────────────────────────────────────────
      'symbolIcon.arrayForeground': p.red,
      'symbolIcon.booleanForeground': p.red,
      'symbolIcon.classForeground': p.primaryMid,
      'symbolIcon.colorForeground': p.secondaryDim,
      'symbolIcon.constantForeground': p.secondaryDim,
      'symbolIcon.constructorForeground': p.secondary,
      'symbolIcon.enumeratorForeground': p.secondary,
      'symbolIcon.enumeratorMemberForeground': p.secondary,
      'symbolIcon.eventForeground': p.secondary,
      'symbolIcon.fieldForeground': p.secondary,
      'symbolIcon.fileForeground': p.primary,
      'symbolIcon.folderForeground': p.primary,
      'symbolIcon.functionForeground': p.secondary,
      'symbolIcon.interfaceForeground': p.primaryMid,
      'symbolIcon.keyForeground': p.secondary,
      'symbolIcon.keywordForeground': p.red,
      'symbolIcon.methodForeground': p.secondary,
      'symbolIcon.moduleForeground': p.primaryMid,
      'symbolIcon.namespaceForeground': p.primaryMid,
      'symbolIcon.nullForeground': p.secondaryDim,
      'symbolIcon.numberForeground': p.secondaryDim,
      'symbolIcon.objectForeground': p.primaryMid,
      'symbolIcon.operatorForeground': p.red,
      'symbolIcon.packageForeground': p.secondaryDim,
      'symbolIcon.propertyForeground': p.secondary,
      'symbolIcon.referenceForeground': p.secondaryDim,
      'symbolIcon.snippetForeground': p.secondary,
      'symbolIcon.stringForeground': p.secondaryBright,
      'symbolIcon.structForeground': p.red,
      'symbolIcon.textForeground': p.secondaryBright,
      'symbolIcon.typeParameterForeground': p.secondary,
      'symbolIcon.unitForeground': p.secondaryDim,
      'symbolIcon.variableForeground': p.primaryMid,

      // ── Simple Find Widget ──────────────────────────────────
      'simpleFindWidget.sashBorder': '',
    },

    tokenColors: [
      // ── Comments ──────────────────────────────────────────
      {
        scope: ['comment', 'comment keyword', 'comment markup.underline.link', 'comment string', 'comment punctuation.definition', 'comment punctuation', 'comment text'],
        settings: { name: 'Comments and overrides inside comments', fontStyle: 'italic', foreground: t.comment },
      },
      { scope: 'comment storage.type', settings: { name: 'JSDoc storage type', foreground: t.comment } },
      { scope: 'comment entity.name.type', settings: { name: 'JSDoc entity name', foreground: t.commentDoc } },
      { scope: ['comment variable', 'comment variable.other'], settings: { name: 'JSDoc variable', foreground: t.commentDoc } },
      { scope: ['comment keyword', 'comment entity.name.tag', 'entity.name.tag.documentation'], settings: { name: 'PHPDoc keyword', foreground: t.commentDoc } },
      { scope: 'comment keyword.codetag.notation', settings: { name: 'Comment TODO / FIXME', foreground: t.label } },
      { scope: 'comment.git-status.header.remote', settings: { name: 'Git status remote', foreground: t.gitRemote } },
      { scope: 'comment.git-status.header.local', settings: { name: 'Git status local', foreground: t.gitLocal } },
      { scope: 'comment.other.git-status.head', settings: { name: 'Git status head', foreground: t.gitHead } },
      { scope: ['string.quoted.docstring', 'string.quoted.docstring punctuation.definition'], settings: { name: 'Docstring', foreground: t.comment } },

      // ── Constants ─────────────────────────────────────────
      { scope: 'constant', settings: { name: 'Constant', foreground: t.constant } },
      { scope: 'constant.other', settings: { name: 'Constant other', foreground: t.constantOther } },
      { scope: 'constant.other.caps', settings: { name: 'Constant caps', foreground: t.constant } },
      { scope: 'constant.other.placeholder', settings: { name: 'Placeholders', foreground: t.variableParam } },
      { scope: 'constant.other.property', settings: { name: 'Constant as property', foreground: t.constant } },
      { scope: 'constant.other.citation.latex', settings: { name: 'Constant in latex', foreground: t.constant } },
      { scope: 'constant.other.color', settings: { name: 'Constant as color', foreground: t.constant } },
      { scope: 'constant.other.character-class.escape', settings: { name: 'Character class escape', foreground: t.constant } },
      { scope: 'constant.other.key', settings: { name: 'Constant as key', foreground: t.constant } },
      { scope: 'constant.other.symbol', settings: { name: 'Constant as symbol', foreground: t.variableParam } },
      { scope: 'constant.other.elm', settings: { name: 'Constants in elm', foreground: t.class } },
      { scope: 'constant.numeric', settings: { name: 'Number', foreground: t.number } },
      { scope: 'constant.language', settings: { name: 'Language constant', foreground: t.constant } },
      { scope: 'constant.character.escape', settings: { name: 'Character escape', foreground: t.constant } },
      { scope: 'constant.numeric.line-number.find-in-files', settings: { name: 'Search result line numbers', foreground: p.primaryGhost } },
      { scope: 'constant.numeric.line-number.match.find-in-files', settings: { name: 'Search result matched line numbers', foreground: t.string } },

      // ── Entity Names ──────────────────────────────────────
      { scope: 'entity.name.section', settings: { name: 'Sections', foreground: t.heading } },
      { scope: ['entity.name.function', 'entity.name.function.templated', 'entity.name.function.member.static'], settings: { name: 'Functions', foreground: t.function } },
      { scope: ['entity.name.type.class.templated', 'entity.name.type.class.generic', 'entity.name.type.namespace'], settings: { name: 'Class template', foreground: t.class } },
      { scope: 'entity.name.label', settings: { name: 'Label', foreground: t.label } },
      { scope: 'entity.name.function.preprocessor', settings: { name: 'Macros', foreground: t.class } },
      { scope: 'entity.name', settings: { name: 'Entity name', foreground: t.function } },
      { scope: 'entity.name.class', settings: { name: 'Class name', foreground: t.class } },
      { scope: 'entity.name.constant', settings: { name: 'Constant name', foreground: t.constant } },
      { scope: 'entity.name.namespace', settings: { name: 'Namespace', foreground: t.class } },
      { scope: 'entity.other.inherited-class', settings: { name: 'Inherited class', fontStyle: 'italic', foreground: t.class } },
      { scope: 'entity.name.function', settings: { name: 'Function name', foreground: t.function } },
      { scope: ['entity.name.tag', 'entity.name.tag.js.jsx support.class.component.js.jsx', 'entity.name.tag support.class.component', 'source.vue support.class.component'], settings: { name: 'Tag name', foreground: t.tag } },
      { scope: 'source.ansible entity.name.tag', settings: { name: 'Tag name (Ansible)', foreground: t.class } },
      { scope: 'entity.name.function.operator', settings: { name: 'Operator', foreground: t.keyword } },
      { scope: ['meta.brackets entity.name.function.operator', 'punctuation.separator entity.name.function.operator'], settings: { name: 'Operator in brackets', foreground: t.operatorMeta } },
      { scope: ['entity.name.type', 'entity.name.type.class.reference', 'entity.name.type.class.value'], settings: { name: 'Entity name type', foreground: t.type } },
      { scope: 'entity.other.attribute-name', settings: { name: 'Tag attribute', fontStyle: 'italic', foreground: t.attribute } },
      { scope: ['entity.other.attribute-name.class.css', 'entity.other.attribute-name.parent-selector-suffix.css', 'entity.other.attribute-name.parent-selector-suffix.css punctuation.definition.entity.css', 'entity.other.attribute-name.css', 'entity.other.animation-name.css'], settings: { name: 'CSS class', foreground: t.cssClass } },
      { scope: 'entity.other.attribute-name.id.css', settings: { name: 'CSS id', foreground: t.cssId } },
      { scope: ['entity.other.attribute-name.pseudo-class.css', 'entity.other.pseudo-class.css', 'entity.other.pseudo-element.css'], settings: { name: 'CSS pseudo class', fontStyle: 'italic', foreground: t.cssPseudo } },
      { scope: ['entity.name.function', 'support.function'], settings: { name: 'Function names / calls', foreground: t.function } },
      { scope: 'entity.other.git-status.hex', settings: { name: 'Git status commit hex', foreground: t.gitHash } },
      { scope: 'entity.other.jinja2.delimiter', settings: { name: 'Jinja delimiters', foreground: t.operatorMeta } },
      { scope: 'entity.name.operator.custom-literal', settings: { name: 'Custom literal', foreground: t.markup } },
      { scope: 'entity.name.operator.custom-literal.string', settings: { name: 'Custom literal string', foreground: t.string } },
      { scope: 'entity.name.operator.custom-literal.number', settings: { name: 'Custom literal number', foreground: t.number } },
      { scope: 'entity.name.type.rust', settings: { name: 'Rust type', foreground: t.class } },
      { scope: 'entity.name.lifetime.rust', settings: { name: 'Rust lifetime', foreground: t.keyword } },

      // ── Invalid ───────────────────────────────────────────
      { scope: 'invalid', settings: { name: 'Invalid', foreground: t.invalid, fontStyle: 'italic underline' } },
      { scope: 'invalid.deprecated', settings: { name: 'Invalid deprecated', foreground: t.invalidDeprecated, fontStyle: 'italic underline' } },

      // ── Keywords ──────────────────────────────────────────
      { scope: 'keyword', settings: { name: 'Keyword', foreground: t.keyword } },
      { scope: 'keyword.control', settings: { name: 'Control keyword', foreground: t.keyword } },
      { scope: 'keyword.control.directive', settings: { name: 'Keyword control directive', foreground: t.keyword } },
      { scope: ['keyword.operator', 'keyword.operator.member', 'keyword.operator.new'], settings: { name: 'Operator', foreground: t.operator } },
      { scope: 'keyword.other.substitution', settings: { name: 'Substitution string', foreground: t.operatorMeta } },
      { scope: ['keyword.other.template.begin', 'keyword.other.template.end'], settings: { name: 'Template literal begin / end', foreground: t.keyword } },
      { scope: ['keyword.operator.heading.restructuredtext', 'keyword.operator.table.row.restructuredtext keyword.operator.table.data.restructuredtext'], settings: { name: 'RestructuredText heading', foreground: t.operatorMeta } },
      { scope: 'keyword.other.parenthesis.elm', settings: { name: 'Elm parenthesis', foreground: t.operatorMeta } },
      { scope: ['keyword.other.fn.rust', 'keyword.other.rust', 'keyword.other.unsafe.rust', 'keyword.other.where.rust'], settings: { name: 'Rust keywords', foreground: t.class } },
      { scope: ['keyword.control.rust', 'keyword.operator.misc.rust'], settings: { name: 'Rust control', foreground: t.keyword } },
      { scope: ['keyword.declaration.class.ruby', 'keyword.declaration.function.ruby', 'keyword.declaration.namespace.ruby'], settings: { name: 'Ruby declarations', foreground: t.keyword } },

      // ── Markup ────────────────────────────────────────────
      { scope: 'markup.italic', settings: { name: 'Italic', fontStyle: 'italic' } },
      { scope: 'markup.bold', settings: { name: 'Bold', fontStyle: 'bold' } },
      { scope: 'markup.heading', settings: { name: 'Heading', foreground: t.heading } },
      { scope: 'markup.raw', settings: { name: 'Raw', foreground: t.markupRaw } },
      { scope: 'markup.underline', settings: { name: 'Underline', fontStyle: 'underline' } },
      { scope: 'markup.underline.link', settings: { name: 'Link', foreground: t.link } },
      { scope: ['markup.inserted', 'markup.inserted punctuation.definition.inserted'], settings: { name: 'Diff inserted', foreground: t.link } },
      { scope: ['markup.deleted', 'markup.deleted punctuation.definition.deleted'], settings: { name: 'Diff deleted', foreground: t.keyword } },
      { scope: ['markup.changed', 'markup.changed punctuation.definition.changed'], settings: { name: 'Diff changed', foreground: t.heading } },
      { scope: ['markup.ignored', 'markup.ignored punctuation.definition.ignored'], settings: { name: 'Diff ignored', foreground: t.operatorMeta } },
      { scope: 'markup.untracked', settings: { name: 'Diff untracked', foreground: t.operatorMeta } },
      { scope: 'markup.quote', settings: { name: 'Markup quote', fontStyle: 'italic' } },

      // ── Meta ──────────────────────────────────────────────
      { scope: ['meta.brace.round', 'meta.brace.square', 'meta.brace.curly', 'meta.delimiter.comma.js', 'meta.function-call.without-arguments.js', 'meta.function-call.method.without-arguments.js'], settings: { name: 'Braces, delimiters', foreground: t.punctuation } },
      { scope: ['meta.function-call.generic.python', 'support.function.builtin.python'], settings: { name: 'Function call (Python)', foreground: t.function } },
      { scope: 'meta.function-call.python meta.function-call.arguments.python', settings: { name: 'Function arguments (Python)', foreground: t.markup } },
      { scope: 'meta.interpolation', settings: { name: 'Interpolation strings', foreground: t.interpolation } },
      { scope: 'meta.instance.constructor', settings: { name: 'Constructor', foreground: t.function } },
      { scope: ['meta.attribute-with-value.class string', 'meta.attribute.class.html string'], settings: { name: 'Class string name', foreground: t.cssClass } },
      { scope: ['meta.attribute-with-value.id string', 'meta.attribute.id.html string'], settings: { name: 'ID string name', foreground: t.cssId } },
      { scope: 'source.json meta.mapping.key string', settings: { name: 'JSON keys', foreground: t.jsonKey } },
      { scope: 'source.yaml meta.mapping.key string', settings: { name: 'YAML keys', foreground: t.yamlKey } },
      { scope: 'meta.object.member', settings: { name: 'Object members', foreground: t.markup } },
      { scope: 'meta.property-list.css variable.other', settings: { name: 'SCSS Variable', foreground: t.scssVar } },
      { scope: ['entity.name.constant.preprocessor', 'meta.preprocessor'], settings: { name: 'Preprocessor', foreground: t.constant } },
      { scope: 'meta.diff.git-diff.header', settings: { name: 'Git diff header', foreground: t.heading } },
      { scope: 'meta.type_params.rust', settings: { name: 'Rust type params', foreground: t.markup } },
      { scope: ['meta.attribute.rust', 'meta.annotation.rust', 'variable.language.rust', 'variable.annotation.rust', 'meta.annotation.rust string', 'meta.annotation.rust keyword', 'meta.annotation.rust keyword.operator', 'meta.attribute.rust string'], settings: { name: 'Rust attributes', foreground: t.commentDoc } },
      { scope: ['meta.type variable', 'meta.type variable.other.readwrite', 'variable.annotation', 'meta.decorator variable.other.readwrite'], settings: { name: 'Type annotation', foreground: t.constant } },

      // ── Punctuation ───────────────────────────────────────
      { scope: 'punctuation', settings: { name: 'Punctuation', foreground: t.punctuation } },
      { scope: ['punctuation.definition.tag', 'punctuation.definition.tag source', 'punctuation.definition.group.begin.ruby', 'punctuation.definition.group.end.ruby', 'punctuation.definition.group.begin.css', 'punctuation.definition.group.end.css', 'punctuation.definition.string.end.html source.css', 'punctuation.definition.block', 'punctuation.definition.parameters.begin', 'punctuation.definition.parameters.end', 'punctuation.separator.parameter', 'punctuation.accessor', 'punctuation.terminator'], settings: { name: 'Punctuation tags', foreground: t.punctuation } },
      { scope: 'punctuation.definition.group', settings: { name: 'Group (regex)', foreground: t.markup } },
      { scope: 'punctuation.definition.comment', settings: { name: 'Comment start / end', foreground: t.punctuationComment } },
      { scope: ['punctuation.definition.variable', 'punctuation.definition.keyword.scss', 'punctuation.definition.entity.css'], settings: { name: 'Variable indicator', foreground: t.punctuationVar } },
      { scope: ['punctuation.section.embedded', 'punctuation.section.embedded entity.name.tag', 'punctuation.section.embedded constant.other', 'punctuation.section.embedded source', 'punctuation.section.embedded.begin'], settings: { name: 'Punctuation section embedded', foreground: t.embedded } },
      { scope: ['punctuation.template-string.element.begin', 'punctuation.template-string.element.end', 'punctuation.definition.string.template.begin', 'punctuation.definition.string.template.end', 'string.quoted.template punctuation.definition.string.begin', 'string.quoted.template punctuation.definition.string.end', 'punctuation.definition.template-expression.begin', 'punctuation.definition.template-expression.end'], settings: { name: 'Punctuation template string', foreground: t.keyword } },
      { scope: ['meta.paragraph.markdown meta.dummy.line-break', 'meta.paragraph.markdown meta.hard-line-break.markdown'], settings: { name: 'Hard line break in Markdown', background: t.constant } },
      { scope: 'markup.underline.link punctuation', settings: { name: 'Punctuation in markdown links', foreground: t.link } },
      { scope: ['meta.brace.round', 'meta.brace.square', 'keyword.operator.type.annotation', 'meta.type storage.modifier.array'], settings: { name: 'Meta braces', foreground: t.punctuation } },

      // ── Regions ───────────────────────────────────────────
      { scope: 'region.redish', settings: { name: 'Region red', foreground: p.red, background: alpha(p.red, '59') } },
      { scope: 'region.orangish', settings: { name: 'Region orange', foreground: p.secondary, background: alpha(p.secondary, '59') } },
      { scope: 'region.yellowish', settings: { name: 'Region yellow', foreground: p.secondaryBright, background: alpha(p.secondaryBright, '59') } },
      { scope: 'region.greenish', settings: { name: 'Region green', foreground: p.secondary, background: alpha(p.secondary, '59') } },
      { scope: 'region.bluish', settings: { name: 'Region blue', foreground: p.primaryMid, background: alpha(p.primaryMid, '59') } },
      { scope: 'region.purplish', settings: { name: 'Region purple', foreground: p.secondaryDim, background: alpha(p.secondaryDim, '59') } },
      { scope: 'region.pinkish', settings: { name: 'Region pink', foreground: p.red, background: alpha(p.red, '59') } },
      { scope: 'region.whitish', settings: { name: 'Region white', foreground: p.white } },

      // ── Source ────────────────────────────────────────────
      { scope: 'source', settings: { name: 'Source', foreground: t.markup } },
      { scope: ['source.scss', 'source.sass'], settings: { name: 'SASS, SCSS default', foreground: t.punctuation } },
      { scope: ['source.sass variable.other', 'source.sass variable.sass', 'source.scss variable.other', 'source.scss variable.scss', 'source.scss variable.sass', 'source.css variable.other', 'source.css variable.scss', 'source.less variable.other', 'source.less variable.other.less', 'source.less variable.declaration.less'], settings: { name: 'SASS, SCSS and LESS variables', fontStyle: 'italic', foreground: t.scssVar } },
      { scope: 'source.git-show.commit.sha', settings: { name: 'Git SHA', foreground: t.gitHash } },
      { scope: ['source.git-show.author', 'source.git-show.date', 'source.git-diff.command', 'source.git-diff.command meta.diff.git-diff.header.from-file', 'source.git-diff.command meta.diff.git-diff.header.to-file'], settings: { name: 'Git metadata', foreground: t.punctuation } },
      { scope: ['source.git-show meta.diff.git-diff.header.extended.index.from-sha', 'source.git-show meta.diff.git-diff.header.extended.index.to-sha'], settings: { name: 'Git diff header hash', foreground: t.gitHash } },
      { scope: 'source.git-show meta.diff.range.unified', settings: { name: 'Git diff header range', foreground: t.diffRange } },
      { scope: ['source.git-show meta.diff.header.from-file', 'source.git-show meta.diff.header.to-file'], settings: { name: 'Git diff header files', foreground: t.punctuation } },

      // ── Storage ───────────────────────────────────────────
      { scope: 'storage', settings: { name: 'Storage', foreground: t.storage } },
      { scope: 'storage.type', settings: { name: 'Storage type', fontStyle: 'italic', foreground: t.storageType } },
      { scope: 'storage.type.extends', settings: { name: 'Extends', fontStyle: 'normal', foreground: t.storage } },
      { scope: 'storage.type.function.arrow', settings: { name: 'Fat arrow function', fontStyle: 'normal', foreground: t.storage } },
      { scope: ['storage.modifier', 'storage.type.modifier'], settings: { name: 'Storage modifier', fontStyle: 'italic', foreground: t.storage } },
      { scope: 'storage.class.restructuredtext.ref', settings: { name: 'RestructuredText refs', foreground: t.constant } },
      { scope: ['storage.modifier.visibility.rust', 'storage.modifier.lifetime.rust'], settings: { name: 'Rust visibility', foreground: t.keyword } },
      { scope: ['storage.modifier.const.rust', 'storage.modifier.dyn.rust', 'storage.modifier.mut.rust', 'storage.modifier.static.rust', 'storage.type.rust', 'storage.type.core.rust', 'storage.class.std.rust'], settings: { name: 'Rust storage types', foreground: t.storageType } },
      { scope: ['storage.type.rust', 'storage.modifier.const.rust', 'storage.modifier.dyn.rust', 'storage.modifier.mut.rust', 'storage.modifier.static.rust', 'keyword.other.rust', 'keyword.other.where.rust'], settings: { name: 'Rust storage (adjusted)', foreground: t.keyword } },
      { scope: 'storage.modifier.import.java', settings: { name: 'Imported Java libraries', foreground: t.markup } },

      // ── Strings ───────────────────────────────────────────
      { scope: 'string', settings: { name: 'String', foreground: t.string } },
      { scope: 'string.unquoted.label', settings: { name: 'String label', foreground: t.markup } },
      { scope: 'string source', settings: { name: 'Source in template string', foreground: t.markup } },
      { scope: ['string source punctuation.section.embedded', 'string punctuation.definition.string source'], settings: { name: 'Embedded punctuation in template string', foreground: t.punctuation } },
      { scope: ['string.other.link.title', 'string.other.link.description'], settings: { name: 'Link title', foreground: t.linkTitle } },
      { scope: 'string.other.link.description.title', settings: { name: 'Link description', foreground: t.linkDesc } },
      { scope: ['string.regexp punctuation.definition.string.begin', 'string.regexp punctuation.definition.string.end'], settings: { name: 'String regexp begin / end', foreground: t.keyword } },
      { scope: ['string.other.ref', 'string.other.restructuredtext.ref'], settings: { name: 'RestructuredText refs', foreground: t.link } },
      { scope: 'string.other.git-status.help.key', settings: { name: 'Git status help key', foreground: t.commentDoc } },
      { scope: 'string.other.git-status.remote', settings: { name: 'Git status remote', foreground: t.gitRemote } },

      // ── Support ───────────────────────────────────────────
      { scope: 'support.constant', settings: { name: 'Library constant', foreground: t.class } },
      { scope: 'support.constant.handlebars', settings: { name: 'Handlebars start / end', foreground: t.punctuation } },
      { scope: 'support.type.vendor-prefix.css', settings: { name: 'Vendor prefix', foreground: t.commentDoc } },
      { scope: 'support.function', settings: { name: 'Support function', foreground: t.function } },
      { scope: 'support.macro', settings: { name: 'Support macro', foreground: t.function } },
      { scope: 'support.function.delimiter.elm', settings: { name: 'Elm function brackets', foreground: t.punctuation } },
      { scope: ['support.type', 'entity.name.type.object.console'], settings: { name: 'Library type', fontStyle: 'italic', foreground: t.type } },
      { scope: ['support.variable', 'support.variable.property'], settings: { name: 'Support variables', foreground: t.class } },
      { scope: 'support.type.property-name', settings: { name: 'Library type property / JSON keys', fontStyle: 'normal', foreground: t.markup } },
      { scope: 'support.class', settings: { name: 'Library class', foreground: t.class } },
      { scope: 'support.constant.core.rust', settings: { name: 'Rust support constant', foreground: t.constant } },
      { scope: ['comment support', 'comment support.class'], settings: { name: 'Comment support', foreground: t.comment } },

      // ── Text ──────────────────────────────────────────────
      { scope: 'text', settings: { name: 'Text', foreground: t.markup } },
      { scope: 'text.find-in-files', settings: { name: 'Search result', foreground: t.markup } },

      // ── Variables ─────────────────────────────────────────
      { scope: ['variable', 'variable.other'], settings: { name: 'Variable', foreground: t.variable } },
      { scope: ['variable.parameter', 'parameters variable.function'], settings: { name: 'Function arguments', fontStyle: 'italic', foreground: t.variableParam } },
      { scope: ['variable.language', 'variable.parameter.function.language.special.self.python', 'variable.parameter.function.language.special.cls.python'], settings: { name: 'Language variables (this, self, super)', fontStyle: 'italic', foreground: t.variableLang } },
      { scope: 'variable.language.arguments', settings: { name: 'Arguments variable', foreground: t.constant } },
      { scope: 'variable.other.class', settings: { name: 'Library function', foreground: t.class } },
      { scope: 'variable.other.constant', settings: { name: 'Immutable variables', foreground: t.constant } },
      { scope: 'variable.other.readwrite', settings: { name: 'Read/write variables', foreground: t.variable } },
      { scope: 'variable.other.member', settings: { name: 'Member variables', foreground: t.variable } },
      { scope: 'variable.other.enummember', settings: { name: 'Enum member', foreground: t.constant } },
      { scope: ['variable.other.property', 'variable.other.property.static', 'variable.other.event'], settings: { name: 'Variable property', foreground: t.variable } },
      { scope: 'variable.function', settings: { name: 'Variable function', foreground: t.function } },
      { scope: 'variable.other.substitution', settings: { name: 'Substitution', foreground: t.variableParam } },
      { scope: ['source.ruby variable.other.readwrite.instance.ruby', 'source.ruby variable.other.readwrite.class.ruby'], settings: { name: 'Ruby instance variables', foreground: t.constant } },
      { scope: 'source.jinja2 variable.other.jinja2.block', settings: { name: 'Jinja2 variable block', foreground: t.function } },
      { scope: 'source.jinja2 variable.other.jinja2', settings: { name: 'Jinja2 variable', foreground: t.variableParam } },
    ],
  };
}

module.exports = buildTheme;
