const tokenMap = require('./tokens');

const alpha = (color, a) => color + a;

// ── Theme Builder ───────────────────────────────────────────
function buildTheme(name, p) {
  const t = tokenMap(p);

  return {
    name,
    type: 'dark',
    author: 'nathanmillwater',
    colorSpaceName: 'sRGB',

    colors: {
      // ── Activity Bar ──────────────────────────────────────
      'activityBar.activeFocusBorder': p.yellow,
      'activityBar.background': p.bgDeepest,
      'activityBar.border': p.bgDeepest,
      'activityBar.foreground': p.fgSoft,
      'activityBar.inactiveForeground': p.fgFaint,
      'activityBarBadge.background': p.yellow,
      'activityBarBadge.foreground': p.bg,
      'activityBarTop.background': p.bgDeep,
      'activityBarTop.foreground': p.fgSoft,
      'activityBarTop.inactiveForeground': p.fgFaint,

      // ── Badge ─────────────────────────────────────────────
      'badge.background': p.yellow,
      'badge.foreground': p.bg,

      // ── Banner ────────────────────────────────────────────
      'banner.background': p.bgElevated,
      'banner.foreground': p.fgSoft,
      'banner.iconForeground': p.fgSoft,

      // ── Breadcrumb ────────────────────────────────────────
      'breadcrumb.activeSelectionForeground': p.fg,
      'breadcrumb.focusForeground': p.fgSoft,
      'breadcrumb.foreground': p.fgMuted,
      'breadcrumbPicker.background': p.bg,

      // ── Buttons ───────────────────────────────────────────
      'button.background': p.bgElevated,
      'button.foreground': p.fg,
      'button.hoverBackground': p.bgOverlay,
      'button.secondaryBackground': p.bgElevated,
      'button.secondaryForeground': p.fgSoft,
      'button.secondaryHoverBackground': p.bgOverlay,
      'button.separator': p.bg,

      // ── Charts ────────────────────────────────────────────
      'charts.blue': p.cyan,
      'charts.foreground': p.fg,
      'charts.green': p.green,
      'charts.lines': p.fgDim,
      'charts.orange': p.orange,
      'charts.purple': p.purple,
      'charts.red': p.red,
      'charts.yellow': p.yellow,

      // ── Chat ──────────────────────────────────────────────
      'chat.avatarBackground': p.bg,
      'chat.avatarForeground': p.purple,
      'chat.requestBackground': p.bgElevated,
      'chat.requestBorder': p.bgOverlay,
      'chat.slashCommandBackground': p.transparent,
      'chat.slashCommandForeground': p.yellow,

      // ── Checkbox ──────────────────────────────────────────
      'checkbox.background': p.bgElevated,
      'checkbox.border': p.bgOverlay,
      'checkbox.foreground': p.yellow,

      // ── Command Center ────────────────────────────────────
      'commandCenter.activeBackground': p.bg,
      'commandCenter.activeForeground': p.fgSoft,
      'commandCenter.background': p.bgDeep,
      'commandCenter.border': p.bg,
      'commandCenter.debuggingBackground': p.bgDeep,
      'commandCenter.foreground': p.fgMuted,

      // ── Debug Console ─────────────────────────────────────
      'debugConsole.errorForeground': p.red,
      'debugConsole.infoForeground': p.cyan,
      'debugConsole.sourceForeground': p.fg,
      'debugConsole.warningForeground': p.orange,
      'debugConsoleInputIcon.foreground': p.yellow,

      // ── Debug Exception Widget ────────────────────────────
      'debugExceptionWidget.background': p.bgElevated,
      'debugExceptionWidget.border': p.bgDeep,

      // ── Debug Icons ───────────────────────────────────────
      'debugIcon.breakpointCurrentStackframeForeground': p.yellow,
      'debugIcon.breakpointDisabledForeground': p.fgSoft,
      'debugIcon.breakpointForeground': p.red,
      'debugIcon.breakpointStackframeForeground': p.fg,
      'debugIcon.breakpointUnverifiedForeground': p.orange,
      'debugIcon.continueForeground': p.fg,
      'debugIcon.disconnectForeground': p.fg,
      'debugIcon.pauseForeground': p.fg,
      'debugIcon.restartForeground': p.green,
      'debugIcon.startForeground': p.green,
      'debugIcon.stepBackForeground': p.fg,
      'debugIcon.stepIntoForeground': p.fg,
      'debugIcon.stepOutForeground': p.fg,
      'debugIcon.stepOverForeground': p.fg,
      'debugIcon.stopForeground': p.red,

      // ── Debug Token Expression ────────────────────────────
      'debugTokenExpression.boolean': p.orange,
      'debugTokenExpression.error': p.red,
      'debugTokenExpression.name': p.cyan,
      'debugTokenExpression.number': p.purple,
      'debugTokenExpression.string': p.yellow,
      'debugTokenExpression.value': p.fg,

      // ── Debug Toolbar / View ──────────────────────────────
      'debugToolBar.background': p.bgElevated,
      'debugView.exceptionLabelBackground': p.red,
      'debugView.exceptionLabelForeground': p.bg,
      'debugView.stateLabelBackground': p.green,
      'debugView.stateLabelForeground': p.bg,
      'debugView.valueChangedHighlight': p.yellow,

      // ── General Foregrounds ───────────────────────────────
      'descriptionForeground': p.fgMuted,
      'disabledForeground': alpha(p.fg, '26'),
      'errorForeground': p.red,
      'focusBorder': p.fgDim,
      'foreground': p.fg,
      'icon.foreground': p.fgMuted,

      // ── Diff Editor ───────────────────────────────────────
      'diffEditor.diagonalFill': p.bgElevated,
      'diffEditor.insertedLineBackground': alpha(p.green, '19'),
      'diffEditor.insertedTextBackground': alpha(p.green, '19'),
      'diffEditor.move.border': '',
      'diffEditor.moveActive.border': '',
      'diffEditor.removedLineBackground': alpha(p.red, '19'),
      'diffEditor.removedTextBackground': alpha(p.red, '19'),
      'diffEditor.unchangedCodeBackground': p.bgDeep,
      'diffEditor.unchangedRegionBackground': p.bgDeep,
      'diffEditor.unchangedRegionForeground': p.fgSoft,
      'diffEditor.unchangedRegionShadow': p.bgDeepest,
      'diffEditorGutter.insertedLineBackground': alpha(p.green, '19'),
      'diffEditorGutter.removedLineBackground': alpha(p.red, '19'),
      'diffEditorOverview.insertedForeground': alpha(p.green, 'a5'),
      'diffEditorOverview.removedForeground': alpha(p.red, 'a5'),

      // ── Dropdown ──────────────────────────────────────────
      'dropdown.background': p.bgElevated,
      'dropdown.border': p.bgOverlay,
      'dropdown.foreground': p.fgMuted,
      'dropdown.listBackground': p.bgElevated,

      // ── Editor ────────────────────────────────────────────
      'editor.background': p.bg,
      'editor.findMatchBackground': alpha(p.fg, '26'),
      'editor.findMatchBorder': p.yellow,
      'editor.findMatchHighlightBackground': alpha(p.fg, '26'),
      'editor.findMatchHighlightBorder': p.transparent,
      'editor.findRangeHighlightBackground': alpha(p.fg, '0c'),
      'editor.findRangeHighlightBorder': p.transparent,
      'editor.focusedStackFrameHighlightBackground': alpha(p.fgSoft, '26'),
      'editor.foldBackground': alpha(p.fg, '0c'),
      'editor.foreground': p.fg,
      'editor.hoverHighlightBackground': alpha(p.fg, '0c'),
      'editor.inactiveSelectionBackground': alpha(p.fg, '0c'),
      'editor.inlineValuesBackground': p.bgOverlay,
      'editor.inlineValuesForeground': p.fgSoft,
      'editor.lineHighlightBackground': alpha(p.fg, '0c'),
      'editor.lineHighlightBorder': p.transparent,
      'editor.linkedEditingBackground': p.bgElevated,
      'editor.rangeHighlightBackground': p.bgElevated,
      'editor.rangeHighlightBorder': p.bgElevated,
      'editor.selectionBackground': alpha(p.fgSoft, '26'),
      'editor.selectionHighlightBackground': alpha(p.fg, '26'),
      'editor.selectionHighlightBorder': p.transparent,
      'editor.stackFrameHighlightBackground': alpha(p.fgSoft, '26'),
      'editor.wordHighlightBackground': alpha(p.fg, '26'),
      'editor.wordHighlightBorder': p.transparent,
      'editor.wordHighlightStrongBackground': alpha(p.fg, '26'),
      'editor.wordHighlightStrongBorder': p.transparent,

      // ── Editor Bracket Highlighting ───────────────────────
      'editorBracketHighlight.foreground1': p.red,
      'editorBracketHighlight.foreground2': p.orange,
      'editorBracketHighlight.foreground3': p.yellow,
      'editorBracketHighlight.foreground4': p.green,
      'editorBracketHighlight.foreground5': p.cyan,
      'editorBracketHighlight.foreground6': p.purple,
      'editorBracketHighlight.unexpectedBracket.foreground': p.red,
      'editorBracketMatch.background': p.bg,
      'editorBracketMatch.border': p.fgDim,
      'editorBracketPairGuide.activeBackground1': p.red,
      'editorBracketPairGuide.activeBackground2': p.orange,
      'editorBracketPairGuide.activeBackground3': p.yellow,
      'editorBracketPairGuide.activeBackground4': p.green,
      'editorBracketPairGuide.activeBackground5': p.cyan,
      'editorBracketPairGuide.activeBackground6': p.purple,
      'editorBracketPairGuide.background1': alpha(p.red, '59'),
      'editorBracketPairGuide.background2': alpha(p.orange, '59'),
      'editorBracketPairGuide.background3': alpha(p.yellow, '59'),
      'editorBracketPairGuide.background4': alpha(p.green, '59'),
      'editorBracketPairGuide.background5': alpha(p.cyan, '59'),
      'editorBracketPairGuide.background6': alpha(p.purple, '59'),

      // ── Editor Code Lens / Cursor ─────────────────────────
      'editorCodeLens.foreground': p.fgDim,
      'editorCursor.background': p.bg,
      'editorCursor.foreground': p.fg,

      // ── Editor Errors / Warnings / Info ───────────────────
      'editorError.background': p.transparent,
      'editorError.border': p.transparent,
      'editorError.foreground': p.red,
      'editorGhostText.foreground': p.fgDim,
      'editorWarning.background': p.transparent,
      'editorWarning.border': p.transparent,
      'editorWarning.foreground': p.orange,
      'editorInfo.background': p.transparent,
      'editorInfo.border': p.bg,
      'editorInfo.foreground': p.cyan,
      'editorHint.border': p.bg,
      'editorHint.foreground': p.purple,

      // ── Editor Groups ─────────────────────────────────────
      'editorGroup.border': p.bgDeep,
      'editorGroup.dropBackground': alpha(p.bgDeep, 'bf'),
      'editorGroup.emptyBackground': p.bgDeepest,
      'editorGroup.focusedEmptyBorder': p.bgDeep,
      'editorGroupHeader.noTabsBackground': p.bg,
      'editorGroupHeader.tabsBackground': p.bg,
      'editorGroupHeader.tabsBorder': p.bg,

      // ── Editor Gutter ─────────────────────────────────────
      'editorGutter.addedBackground': p.green,
      'editorGutter.background': p.bg,
      'editorGutter.deletedBackground': p.red,
      'editorGutter.foldingControlForeground': p.fgSoft,
      'editorGutter.modifiedBackground': p.orange,

      // ── Editor Hover / Suggest / Inlay ────────────────────
      'editorHoverWidget.background': p.bgElevated,
      'editorHoverWidget.border': p.bgDeep,
      'editorIndentGuide.background': p.bgElevated,
      'editorInlayHint.background': p.bgElevated,
      'editorInlayHint.foreground': p.fgMuted,
      'editorInlayHint.parameterBackground': p.bgElevated,
      'editorInlayHint.parameterForeground': p.fgDim,
      'editorInlayHint.typeBackground': p.bgElevated,
      'editorInlayHint.typeForeground': p.fgDim,

      // ── Editor Light Bulb ─────────────────────────────────
      'editorLightBulb.foreground': p.yellow,
      'editorLightBulbAi.foreground': p.yellow,
      'editorLightBulbAutoFix.foreground': p.green,

      // ── Editor Line Numbers ───────────────────────────────
      'editorLineNumber.activeForeground': p.fgSoft,
      'editorLineNumber.foreground': p.fgFaint,
      'editorLink.activeForeground': p.cyan,

      // ── Editor Marker Navigation ──────────────────────────
      'editorMarkerNavigation.background': p.bgElevated,
      'editorMarkerNavigationError.background': p.red,
      'editorMarkerNavigationInfo.background': p.cyan,
      'editorMarkerNavigationWarning.background': p.orange,

      // ── Editor Overview Ruler ─────────────────────────────
      'editorOverviewRuler.addedForeground': p.green,
      'editorOverviewRuler.border': p.bg,
      'editorOverviewRuler.currentContentForeground': p.bgElevated,
      'editorOverviewRuler.deletedForeground': p.red,
      'editorOverviewRuler.errorForeground': p.red,
      'editorOverviewRuler.findMatchForeground': alpha(p.fg, '26'),
      'editorOverviewRuler.incomingContentForeground': p.bgElevated,
      'editorOverviewRuler.infoForeground': p.cyan,
      'editorOverviewRuler.modifiedForeground': p.orange,
      'editorOverviewRuler.rangeHighlightForeground': alpha(p.fg, '26'),
      'editorOverviewRuler.selectionHighlightForeground': alpha(p.fg, '26'),
      'editorOverviewRuler.warningForeground': p.orange,
      'editorOverviewRuler.wordHighlightForeground': alpha(p.fg, '26'),
      'editorOverviewRuler.wordHighlightStrongForeground': alpha(p.fg, '26'),

      // ── Editor Pane / Ruler / Sticky Scroll ───────────────
      'editorPane.background': p.bg,
      'editorRuler.foreground': p.fgFaint,
      'editorStickyScroll.background': p.bg,
      'editorStickyScroll.border': p.bgElevated,
      'editorStickyScroll.shadow': p.bg,
      'editorStickyScrollHover.background': alpha(p.fg, '0c'),

      // ── Editor Suggest Widget ─────────────────────────────
      'editorSuggestWidget.background': p.bgElevated,
      'editorSuggestWidget.border': p.bgDeep,
      'editorSuggestWidget.foreground': p.fgSoft,
      'editorSuggestWidget.highlightForeground': p.fg,
      'editorSuggestWidget.selectedBackground': p.bgOverlay,

      // ── Editor Unnecessary / Whitespace ───────────────────
      'editorUnnecessaryCode.opacity': '#000000a5',
      'editorWhitespace.foreground': p.fgFaint,
      'editorWidget.background': p.bgElevated,
      'editorWidget.border': p.bgDeep,

      // ── Extensions ────────────────────────────────────────
      'extensionBadge.remoteBackground': p.green,
      'extensionBadge.remoteForeground': p.fg,
      'extensionButton.background': p.bgElevated,
      'extensionButton.foreground': p.fgSoft,
      'extensionButton.hoverBackground': p.bgOverlay,
      'extensionButton.prominentBackground': p.bgElevated,
      'extensionButton.prominentForeground': p.fg,
      'extensionButton.prominentHoverBackground': p.bgOverlay,
      'extensionIcon.preReleaseForeground': p.purple,
      'extensionIcon.sponsorForeground': p.cyan,
      'extensionIcon.starForeground': p.yellow,
      'extensionIcon.verifiedForeground': p.green,

      // ── Git Decorations ───────────────────────────────────
      'gitDecoration.addedResourceForeground': p.green,
      'gitDecoration.conflictingResourceForeground': p.orange,
      'gitDecoration.deletedResourceForeground': p.red,
      'gitDecoration.ignoredResourceForeground': p.fgFaint,
      'gitDecoration.modifiedResourceForeground': p.yellow,
      'gitDecoration.stageDeletedResourceForeground': p.red,
      'gitDecoration.stageModifiedResourceForeground': p.yellow,
      'gitDecoration.untrackedResourceForeground': p.fgSoft,

      // ── Inline Chat ───────────────────────────────────────
      'inlineChat.background': p.bg,
      'inlineChat.border': p.bgDeep,
      'inlineChat.shadow': p.bgDeepest,
      'inlineChatDiff.inserted': alpha(p.green, '19'),
      'inlineChatDiff.removed': alpha(p.green, '19'),

      // ── Input ─────────────────────────────────────────────
      'input.background': p.bgElevated,
      'input.border': p.bgOverlay,
      'input.foreground': p.fg,
      'input.placeholderForeground': p.fgDim,
      'inputOption.activeBackground': p.bgOverlay,
      'inputOption.activeBorder': p.bgOverlay,
      'inputOption.activeForeground': p.fg,
      'inputOption.hoverBackground': p.bgOverlay,
      'inputValidation.errorBackground': p.bgElevated,
      'inputValidation.errorBorder': p.red,
      'inputValidation.errorForeground': p.red,
      'inputValidation.infoBackground': p.bgElevated,
      'inputValidation.infoBorder': p.cyan,
      'inputValidation.infoForeground': p.cyan,
      'inputValidation.warningBackground': p.bgElevated,
      'inputValidation.warningBorder': p.orange,
      'inputValidation.warningForeground': p.orange,

      // ── Interactive ───────────────────────────────────────
      'interactive.activeCodeBorder': p.fgDim,
      'interactive.inactiveCodeBorder': p.bgElevated,

      // ── Keybinding Label ──────────────────────────────────
      'keybindingLabel.background': p.bgOverlay,
      'keybindingLabel.border': p.bgOverlay,
      'keybindingLabel.bottomBorder': p.bgOverlay,
      'keybindingLabel.foreground': p.fgSoft,

      // ── List / Tree ───────────────────────────────────────
      'list.activeSelectionBackground': alpha(p.fg, '0c'),
      'list.activeSelectionForeground': p.yellow,
      'list.dropBackground': alpha(p.bgDeepest, 'bf'),
      'list.errorForeground': p.red,
      'list.focusBackground': p.bg,
      'list.focusForeground': p.fg,
      'list.highlightForeground': p.fg,
      'list.hoverBackground': alpha(p.fg, '0c'),
      'list.hoverForeground': p.fg,
      'list.inactiveFocusBackground': p.bg,
      'list.inactiveSelectionBackground': alpha(p.fgSoft, '0c'),
      'list.inactiveSelectionForeground': p.yellow,
      'list.invalidItemForeground': p.red,
      'list.warningForeground': p.orange,
      'listFilterWidget.background': p.bg,
      'listFilterWidget.noMatchesOutline': p.red,
      'listFilterWidget.outline': p.bg,
      'listFilterWidget.shadow': p.bgDeepest,

      // ── Menu ──────────────────────────────────────────────
      'menu.background': p.bg,
      'menu.border': p.bgDeep,
      'menu.foreground': p.fg,
      'menu.selectionForeground': p.yellow,
      'menu.separatorBackground': p.bgElevated,
      'menubar.selectionForeground': p.fg,

      // ── Merge ─────────────────────────────────────────────
      'merge.border': p.bg,
      'merge.commonContentBackground': alpha(p.fg, '19'),
      'merge.commonHeaderBackground': alpha(p.fg, '26'),
      'merge.currentContentBackground': alpha(p.red, '19'),
      'merge.currentHeaderBackground': alpha(p.red, '26'),
      'merge.incomingContentBackground': alpha(p.green, '19'),
      'merge.incomingHeaderBackground': alpha(p.green, '26'),

      // ── Merge Editor ──────────────────────────────────────
      'mergeEditor.change.background': alpha(p.fg, '19'),
      'mergeEditor.change.word.background': alpha(p.fg, '19'),
      'mergeEditor.conflict.handled.minimapOverViewRuler': p.green,
      'mergeEditor.conflict.handledFocused.border': p.green,
      'mergeEditor.conflict.handledUnfocused.border': p.green,
      'mergeEditor.conflict.unhandled.minimapOverViewRuler': p.red,
      'mergeEditor.conflict.unhandledFocused.border': p.red,
      'mergeEditor.conflict.unhandledUnfocused.border': p.red,

      // ── Minimap ───────────────────────────────────────────
      'minimap.errorHighlight': alpha(p.red, 'a5'),
      'minimap.findMatchHighlight': alpha(p.fgMuted, 'a5'),
      'minimap.infoHighlight': alpha(p.cyan, 'a5'),
      'minimap.selectionHighlight': alpha(p.fgSoft, '26'),
      'minimap.selectionOccurrenceHighlight': alpha(p.fgDim, 'a5'),
      'minimap.warningHighlight': alpha(p.orange, 'a5'),
      'minimapGutter.addedBackground': p.green,
      'minimapGutter.deletedBackground': p.red,
      'minimapGutter.modifiedBackground': p.yellow,

      // ── Notebook ──────────────────────────────────────────
      'notebook.cellBorderColor': p.bgElevated,
      'notebook.cellEditorBackground': alpha(p.bgDeep, '7f'),
      'notebook.cellInsertionIndicator': p.fg,
      'notebook.cellStatusBarItemHoverBackground': p.fgDim,
      'notebook.cellToolbarSeparator': p.bgElevated,
      'notebook.editorBackground': p.bg,
      'notebook.focusedEditorBorder': p.fgDim,
      'notebookStatusErrorIcon.foreground': p.red,
      'notebookStatusRunningIcon.foreground': p.fg,
      'notebookStatusSuccessIcon.foreground': p.green,

      // ── Notifications ─────────────────────────────────────
      'notificationCenter.border': p.bgDeep,
      'notificationCenterHeader.background': p.bgElevated,
      'notificationCenterHeader.foreground': p.fgMuted,
      'notificationLink.foreground': p.yellow,
      'notifications.background': p.bgElevated,
      'notifications.border': p.bgDeep,
      'notifications.foreground': p.fgSoft,
      'notificationsErrorIcon.foreground': p.red,
      'notificationsInfoIcon.foreground': p.cyan,
      'notificationsWarningIcon.foreground': p.orange,
      'notificationToast.border': p.bgDeep,

      // ── Panel ─────────────────────────────────────────────
      'panel.background': p.bgElevated,
      'panel.border': p.bgDeepest,
      'panel.dropBackground': alpha(p.bgDeep, 'bf'),
      'panelStickyScroll.background': p.bgElevated,
      'panelStickyScroll.border': p.bgOverlay,
      'panelStickyScroll.shadow': p.bgElevated,
      'panelTitle.activeBorder': p.yellow,
      'panelTitle.activeForeground': p.yellow,
      'panelTitle.inactiveForeground': p.fgMuted,

      // ── Peek View ─────────────────────────────────────────
      'peekView.border': p.bgDeep,
      'peekViewEditor.background': p.bgElevated,
      'peekViewEditor.matchHighlightBackground': p.bgOverlay,
      'peekViewEditorGutter.background': p.bgElevated,
      'peekViewResult.background': p.bgElevated,
      'peekViewResult.fileForeground': p.fgMuted,
      'peekViewResult.lineForeground': p.fgMuted,
      'peekViewResult.matchHighlightBackground': p.bgOverlay,
      'peekViewResult.selectionBackground': p.bgElevated,
      'peekViewResult.selectionForeground': p.fg,
      'peekViewTitle.background': p.bgDeep,
      'peekViewTitleDescription.foreground': p.fgMuted,
      'peekViewTitleLabel.foreground': p.fg,

      // ── Picker Group ──────────────────────────────────────
      'pickerGroup.border': p.bg,
      'pickerGroup.foreground': p.fgFaint,

      // ── Ports ─────────────────────────────────────────────
      'ports.iconRunningProcessForeground': p.green,

      // ── Problems ──────────────────────────────────────────
      'problemsErrorIcon.foreground': p.red,
      'problemsInfoIcon.foreground': p.cyan,
      'problemsWarningIcon.foreground': p.orange,

      // ── Profile Badge ─────────────────────────────────────
      'profileBadge.background': p.bgElevated,
      'profileBadge.foreground': p.fgSoft,

      // ── Progress Bar ──────────────────────────────────────
      'progressBar.background': p.fgDim,

      // ── Quick Input ───────────────────────────────────────
      'quickInput.background': p.bgElevated,
      'quickInput.foreground': p.fgMuted,

      // ── Sash ──────────────────────────────────────────────
      'sash.hoverBorder': p.fgDim,

      // ── SCM Graph ─────────────────────────────────────────
      'scmGraph.historyItemHoverLabelForeground': p.bg,
      'scmGraph.foreground1': p.red,
      'scmGraph.foreground2': p.orange,
      'scmGraph.foreground3': p.yellow,
      'scmGraph.foreground4': p.green,
      'scmGraph.foreground5': p.purple,
      'scmGraph.historyItemHoverAdditionsForeground': p.green,
      'scmGraph.historyItemHoverDeletionsForeground': p.red,
      'scmGraph.historyItemRefColor': p.purple,
      'scmGraph.historyItemRemoteRefColor': p.green,
      'scmGraph.historyItemBaseRefColor': p.cyan,
      'scmGraph.historyItemHoverDefaultLabelForeground': p.bg,
      'scmGraph.historyItemHoverDefaultLabelBackground': p.fgDim,

      // ── Scrollbar ─────────────────────────────────────────
      'scrollbar.shadow': p.bg,
      'scrollbarSlider.activeBackground': alpha(p.fg, '59'),
      'scrollbarSlider.background': alpha(p.fgSoft, '26'),
      'scrollbarSlider.hoverBackground': alpha(p.fg, '26'),

      // ── Selection ─────────────────────────────────────────
      'selection.background': alpha(p.fgSoft, '26'),

      // ── Settings ──────────────────────────────────────────
      'settings.checkboxBackground': p.bgElevated,
      'settings.checkboxBorder': p.bgOverlay,
      'settings.checkboxForeground': p.yellow,
      'settings.dropdownBackground': p.bgElevated,
      'settings.dropdownBorder': p.bgOverlay,
      'settings.dropdownForeground': p.fg,
      'settings.dropdownListBorder': p.fgMuted,
      'settings.headerForeground': p.yellow,
      'settings.modifiedItemForeground': p.yellow,
      'settings.modifiedItemIndicator': p.yellow,
      'settings.numberInputBackground': p.bgElevated,
      'settings.numberInputBorder': p.bgOverlay,
      'settings.numberInputForeground': p.fg,
      'settings.rowHoverBackground': alpha(p.fgDim, '0c'),
      'settings.sashBorder': p.bgElevated,
      'settings.settingsHeaderHoverForeground': p.fg,
      'settings.textInputBackground': p.bgElevated,
      'settings.textInputBorder': p.bgOverlay,
      'settings.textInputForeground': p.fg,

      // ── Sidebar ───────────────────────────────────────────
      'sideBar.background': p.bgDeep,
      'sideBar.border': p.bgDeepest,
      'sideBar.dropBackground': alpha(p.bgDeep, 'bf'),
      'sideBar.foreground': p.fgMuted,
      'sideBarSectionHeader.background': p.bgDeep,
      'sideBarSectionHeader.foreground': p.fgDim,
      'sideBarStickyScroll.background': p.bgDeep,
      'sideBarStickyScroll.border': p.bgElevated,
      'sideBarStickyScroll.shadow': p.bgDeep,
      'sideBarTitle.foreground': p.fgFaint,
      'simpleFindWidget.sashBorder': '',

      // ── Status Bar ────────────────────────────────────────
      'statusBar.background': p.bgDeep,
      'statusBar.border': p.bgDeepest,
      'statusBar.debuggingBackground': p.fgDim,
      'statusBar.debuggingBorder': p.bgDeep,
      'statusBar.debuggingForeground': p.fg,
      'statusBar.focusBorder': p.bgElevated,
      'statusBar.foreground': p.fgDim,
      'statusBar.noFolderBackground': p.bgDeep,
      'statusBar.noFolderBorder': p.bgDeepest,
      'statusBar.noFolderForeground': p.fgDim,
      'statusBarItem.activeBackground': p.bg,
      'statusBarItem.errorBackground': p.bg,
      'statusBarItem.errorForeground': p.red,
      'statusBarItem.focusBorder': p.fgDim,
      'statusBarItem.hoverBackground': p.bgDeep,
      'statusBarItem.hoverForeground': p.fg,
      'statusBarItem.prominentBackground': p.bgElevated,
      'statusBarItem.offlineBackground': '',
      'statusBarItem.offlineForeground': '',
      'statusBarItem.prominentHoverBackground': p.bgElevated,
      'statusBarItem.remoteBackground': p.bgDeep,
      'statusBarItem.remoteForeground': p.green,
      'statusBarItem.remoteHoverBackground': p.green,
      'statusBarItem.remoteHoverForeground': p.bg,
      'statusBarItem.warningBackground': p.bg,
      'statusBarItem.warningForeground': p.orange,

      // ── Symbol Icons ──────────────────────────────────────
      'symbolIcon.arrayForeground': p.red,
      'symbolIcon.booleanForeground': p.red,
      'symbolIcon.classForeground': p.cyan,
      'symbolIcon.colorForeground': p.purple,
      'symbolIcon.constantForeground': p.purple,
      'symbolIcon.constructorForeground': p.green,
      'symbolIcon.enumeratorForeground': p.orange,
      'symbolIcon.enumeratorMemberForeground': p.orange,
      'symbolIcon.eventForeground': p.orange,
      'symbolIcon.fieldForeground': p.orange,
      'symbolIcon.fileForeground': p.fgSoft,
      'symbolIcon.folderForeground': p.fgSoft,
      'symbolIcon.functionForeground': p.green,
      'symbolIcon.interfaceForeground': p.cyan,
      'symbolIcon.keyForeground': p.orange,
      'symbolIcon.keywordForeground': p.red,
      'symbolIcon.methodForeground': p.green,
      'symbolIcon.moduleForeground': p.cyan,
      'symbolIcon.namespaceForeground': p.cyan,
      'symbolIcon.nullForeground': p.purple,
      'symbolIcon.numberForeground': p.purple,
      'symbolIcon.objectForeground': p.cyan,
      'symbolIcon.operatorForeground': p.red,
      'symbolIcon.packageForeground': p.purple,
      'symbolIcon.propertyForeground': p.orange,
      'symbolIcon.referenceForeground': p.purple,
      'symbolIcon.snippetForeground': p.green,
      'symbolIcon.stringForeground': p.yellow,
      'symbolIcon.structForeground': p.red,
      'symbolIcon.textForeground': p.yellow,
      'symbolIcon.typeParameterForeground': p.orange,
      'symbolIcon.unitForeground': p.purple,
      'symbolIcon.variableForeground': p.cyan,

      // ── Tabs ──────────────────────────────────────────────
      'tab.activeBackground': p.bg,
      'tab.activeBorder': p.yellow,
      'tab.activeForeground': p.yellow,
      'tab.activeModifiedBorder': p.bgOverlay,
      'tab.border': p.bg,
      'tab.hoverBackground': p.bg,
      'tab.hoverBorder': p.bgOverlay,
      'tab.hoverForeground': p.fg,
      'tab.inactiveBackground': p.bg,
      'tab.inactiveForeground': p.fgMuted,
      'tab.inactiveModifiedBorder': p.bgOverlay,
      'tab.lastPinnedBorder': p.bgOverlay,
      'tab.unfocusedActiveBorder': p.fgMuted,
      'tab.unfocusedActiveForeground': p.fgSoft,
      'tab.unfocusedActiveModifiedBorder': p.bgElevated,
      'tab.unfocusedHoverBackground': p.bg,
      'tab.unfocusedHoverBorder': p.bg,
      'tab.unfocusedHoverForeground': p.fgSoft,
      'tab.unfocusedInactiveForeground': p.fgMuted,
      'tab.unfocusedInactiveModifiedBorder': p.bgElevated,

      // ── Terminal ──────────────────────────────────────────
      'terminal.ansiBlack': p.bgElevated,
      'terminal.ansiBlue': p.orange,
      'terminal.ansiBrightBlack': p.fgDim,
      'terminal.ansiBrightBlue': p.orange,
      'terminal.ansiBrightCyan': p.cyan,
      'terminal.ansiBrightGreen': p.green,
      'terminal.ansiBrightMagenta': p.purple,
      'terminal.ansiBrightRed': p.red,
      'terminal.ansiBrightWhite': p.fg,
      'terminal.ansiBrightYellow': p.yellow,
      'terminal.ansiCyan': p.cyan,
      'terminal.ansiGreen': p.green,
      'terminal.ansiMagenta': p.purple,
      'terminal.ansiRed': p.red,
      'terminal.ansiWhite': p.fg,
      'terminal.ansiYellow': p.yellow,
      'terminal.background': p.bgElevated,
      'terminal.foreground': p.fg,
      'terminal.selectionBackground': alpha(p.fg, '26'),
      'terminalCommandDecoration.defaultBackground': p.fg,
      'terminalCommandDecoration.errorBackground': p.red,
      'terminalCommandDecoration.successBackground': p.green,
      'terminalCursor.background': p.transparent,
      'terminalCursor.foreground': p.fg,

      // ── Testing ───────────────────────────────────────────
      'testing.iconErrored': p.red,
      'testing.iconFailed': p.red,
      'testing.iconPassed': p.green,
      'testing.iconQueued': p.fg,
      'testing.iconSkipped': p.orange,
      'testing.iconUnset': p.fgMuted,
      'testing.message.error.decorationForeground': p.red,
      'testing.message.error.lineBackground': alpha(p.red, '19'),
      'testing.message.info.decorationForeground': p.fg,
      'testing.message.info.lineBackground': alpha(p.fg, '19'),
      'testing.runAction': p.yellow,

      // ── Text ──────────────────────────────────────────────
      'textBlockQuote.background': p.bgElevated,
      'textBlockQuote.border': p.bgElevated,
      'textCodeBlock.background': p.bgElevated,
      'textLink.activeForeground': p.fg,
      'textLink.foreground': p.yellow,
      'textPreformat.foreground': p.fg,
      'textSeparator.foreground': p.fgDim,

      // ── Title Bar ─────────────────────────────────────────
      'titleBar.activeBackground': p.bgDeep,
      'titleBar.activeForeground': p.fgMuted,
      'titleBar.border': p.bgDeepest,
      'titleBar.inactiveBackground': p.bgDeep,
      'titleBar.inactiveForeground': p.fgFaint,

      // ── Tree ──────────────────────────────────────────────
      'tree.inactiveIndentGuidesStroke': p.bg,
      'tree.indentGuidesStroke': p.bgElevated,

      // ── Walk Through / Welcome ────────────────────────────
      'walkThrough.embeddedEditorBackground': p.bgDeep,
      'welcomePage.buttonBackground': p.bgElevated,
      'welcomePage.buttonHoverBackground': p.bgOverlay,
      'welcomePage.progress.background': p.fgDim,
      'welcomePage.progress.foreground': p.fgMuted,
      'welcomePage.tileBackground': p.bgElevated,
      'welcomePage.tileHoverBackground': p.bgOverlay,
      'welcomePage.tileShadow': p.bgDeepest,

      // ── Widget ────────────────────────────────────────────
      'widget.shadow': p.bgDeepest,
    },

    tokenColors: [
      // ── Comments ──────────────────────────────────────────
      {
        scope: ['comment', 'comment keyword', 'comment markup.underline.link', 'comment string', 'comment punctuation.definition', 'comment punctuation', 'comment text'],
        settings: { name: 'Comments and overrides inside comments', fontStyle: 'italic', foreground: t.comment },
      },
      { scope: 'comment storage.type', settings: { name: 'JSDoc storage type', foreground: t.comment } },
      { scope: 'comment entity.name.type', settings: { name: 'JSDoc entity name', foreground: t.commentDoc } },
      { scope: ['comment variable', 'comment variable.other'], settings: { name: 'JSDoc variable', foreground: t.commentDoc } },
      { scope: ['comment keyword', 'comment entity.name.tag', 'entity.name.tag.documentation'], settings: { name: 'PHPDoc keyword', foreground: t.commentDoc } },
      { scope: 'comment keyword.codetag.notation', settings: { name: 'Comment TODO / FIXME', foreground: t.label } },
      { scope: 'comment.git-status.header.remote', settings: { name: 'Git status remote', foreground: t.gitRemote } },
      { scope: 'comment.git-status.header.local', settings: { name: 'Git status local', foreground: t.gitLocal } },
      { scope: 'comment.other.git-status.head', settings: { name: 'Git status head', foreground: t.gitHead } },
      { scope: ['string.quoted.docstring', 'string.quoted.docstring punctuation.definition'], settings: { name: 'Docstring', foreground: t.comment } },

      // ── Constants ─────────────────────────────────────────
      { scope: 'constant', settings: { name: 'Constant', foreground: t.constant } },
      { scope: 'constant.other', settings: { name: 'Constant other', foreground: t.constantOther } },
      { scope: 'constant.other.caps', settings: { name: 'Constant caps', foreground: t.constant } },
      { scope: 'constant.other.placeholder', settings: { name: 'Placeholders', foreground: t.variableParam } },
      { scope: 'constant.other.property', settings: { name: 'Constant as property', foreground: t.constant } },
      { scope: 'constant.other.citation.latex', settings: { name: 'Constant in latex', foreground: t.constant } },
      { scope: 'constant.other.color', settings: { name: 'Constant as color', foreground: t.constant } },
      { scope: 'constant.other.character-class.escape', settings: { name: 'Character class escape', foreground: t.constant } },
      { scope: 'constant.other.key', settings: { name: 'Constant as key', foreground: t.constant } },
      { scope: 'constant.other.symbol', settings: { name: 'Constant as symbol', foreground: t.variableParam } },
      { scope: 'constant.other.elm', settings: { name: 'Constants in elm', foreground: t.class } },
      { scope: 'constant.numeric', settings: { name: 'Number', foreground: t.number } },
      { scope: 'constant.language', settings: { name: 'Language constant', foreground: t.constant } },
      { scope: 'constant.character.escape', settings: { name: 'Character escape', foreground: t.constant } },
      { scope: 'constant.numeric.line-number.find-in-files', settings: { name: 'Search result line numbers', foreground: p.fgFaint } },
      { scope: 'constant.numeric.line-number.match.find-in-files', settings: { name: 'Search result matched line numbers', foreground: t.string } },

      // ── Entity Names ──────────────────────────────────────
      { scope: 'entity.name.section', settings: { name: 'Sections', foreground: t.heading } },
      { scope: ['entity.name.function', 'entity.name.function.templated', 'entity.name.function.member.static'], settings: { name: 'Functions', foreground: t.function } },
      { scope: ['entity.name.type.class.templated', 'entity.name.type.class.generic', 'entity.name.type.namespace'], settings: { name: 'Class template', foreground: t.class } },
      { scope: 'entity.name.label', settings: { name: 'Label', foreground: t.label } },
      { scope: 'entity.name.function.preprocessor', settings: { name: 'Macros', foreground: t.class } },
      { scope: 'entity.name', settings: { name: 'Entity name', foreground: t.function } },
      { scope: 'entity.name.class', settings: { name: 'Class name', foreground: t.class } },
      { scope: 'entity.name.constant', settings: { name: 'Constant name', foreground: t.constant } },
      { scope: 'entity.name.namespace', settings: { name: 'Namespace', foreground: t.class } },
      { scope: 'entity.other.inherited-class', settings: { name: 'Inherited class', fontStyle: 'italic', foreground: t.class } },
      { scope: 'entity.name.function', settings: { name: 'Function name', foreground: t.function } },
      { scope: ['entity.name.tag', 'entity.name.tag.js.jsx support.class.component.js.jsx', 'entity.name.tag support.class.component', 'source.vue support.class.component'], settings: { name: 'Tag name', foreground: t.tag } },
      { scope: 'source.ansible entity.name.tag', settings: { name: 'Tag name (Ansible)', foreground: t.class } },
      { scope: 'entity.name.function.operator', settings: { name: 'Operator', foreground: t.keyword } },
      { scope: ['meta.brackets entity.name.function.operator', 'punctuation.separator entity.name.function.operator'], settings: { name: 'Operator in brackets', foreground: t.operatorMeta } },
      { scope: ['entity.name.type', 'entity.name.type.class.reference', 'entity.name.type.class.value'], settings: { name: 'Entity name type', foreground: t.type } },
      { scope: 'entity.other.attribute-name', settings: { name: 'Tag attribute', fontStyle: 'italic', foreground: t.attribute } },
      { scope: ['entity.other.attribute-name.class.css', 'entity.other.attribute-name.parent-selector-suffix.css', 'entity.other.attribute-name.parent-selector-suffix.css punctuation.definition.entity.css', 'entity.other.attribute-name.css', 'entity.other.animation-name.css'], settings: { name: 'CSS class', foreground: t.cssClass } },
      { scope: 'entity.other.attribute-name.id.css', settings: { name: 'CSS id', foreground: t.cssId } },
      { scope: ['entity.other.attribute-name.pseudo-class.css', 'entity.other.pseudo-class.css', 'entity.other.pseudo-element.css'], settings: { name: 'CSS pseudo class', fontStyle: 'italic', foreground: t.cssPseudo } },
      { scope: ['entity.name.function', 'support.function'], settings: { name: 'Function names / calls', foreground: t.function } },
      { scope: 'entity.other.git-status.hex', settings: { name: 'Git status commit hex', foreground: t.gitHash } },
      { scope: 'entity.other.jinja2.delimiter', settings: { name: 'Jinja delimiters', foreground: t.operatorMeta } },
      { scope: 'entity.name.operator.custom-literal', settings: { name: 'Custom literal', foreground: t.markup } },
      { scope: 'entity.name.operator.custom-literal.string', settings: { name: 'Custom literal string', foreground: t.string } },
      { scope: 'entity.name.operator.custom-literal.number', settings: { name: 'Custom literal number', foreground: t.number } },
      { scope: 'entity.name.type.rust', settings: { name: 'Rust type', foreground: t.class } },
      { scope: 'entity.name.lifetime.rust', settings: { name: 'Rust lifetime', foreground: t.keyword } },

      // ── Invalid ───────────────────────────────────────────
      { scope: 'invalid', settings: { name: 'Invalid', foreground: t.invalid, fontStyle: 'italic underline' } },
      { scope: 'invalid.deprecated', settings: { name: 'Invalid deprecated', foreground: t.invalidDeprecated, fontStyle: 'italic underline' } },

      // ── Keywords ──────────────────────────────────────────
      { scope: 'keyword', settings: { name: 'Keyword', foreground: t.keyword } },
      { scope: 'keyword.control', settings: { name: 'Control keyword', foreground: t.keyword } },
      { scope: 'keyword.control.directive', settings: { name: 'Keyword control directive', foreground: t.keyword } },
      { scope: ['keyword.operator', 'keyword.operator.member', 'keyword.operator.new'], settings: { name: 'Operator', foreground: t.operator } },
      { scope: 'keyword.other.substitution', settings: { name: 'Substitution string', foreground: t.operatorMeta } },
      { scope: ['keyword.other.template.begin', 'keyword.other.template.end'], settings: { name: 'Template literal begin / end', foreground: t.keyword } },
      { scope: ['keyword.operator.heading.restructuredtext', 'keyword.operator.table.row.restructuredtext keyword.operator.table.data.restructuredtext'], settings: { name: 'RestructuredText heading', foreground: t.operatorMeta } },
      { scope: 'keyword.other.parenthesis.elm', settings: { name: 'Elm parenthesis', foreground: t.operatorMeta } },
      { scope: ['keyword.other.fn.rust', 'keyword.other.rust', 'keyword.other.unsafe.rust', 'keyword.other.where.rust'], settings: { name: 'Rust keywords', foreground: t.class } },
      { scope: ['keyword.control.rust', 'keyword.operator.misc.rust'], settings: { name: 'Rust control', foreground: t.keyword } },
      { scope: ['keyword.declaration.class.ruby', 'keyword.declaration.function.ruby', 'keyword.declaration.namespace.ruby'], settings: { name: 'Ruby declarations', foreground: t.keyword } },

      // ── Markup ────────────────────────────────────────────
      { scope: 'markup.italic', settings: { name: 'Italic', fontStyle: 'italic' } },
      { scope: 'markup.bold', settings: { name: 'Bold', fontStyle: 'bold' } },
      { scope: 'markup.heading', settings: { name: 'Heading', foreground: t.heading } },
      { scope: 'markup.raw', settings: { name: 'Raw', foreground: t.markupRaw } },
      { scope: 'markup.underline', settings: { name: 'Underline', fontStyle: 'underline' } },
      { scope: 'markup.underline.link', settings: { name: 'Link', foreground: t.link } },
      { scope: ['markup.inserted', 'markup.inserted punctuation.definition.inserted'], settings: { name: 'Diff inserted', foreground: t.link } },
      { scope: ['markup.deleted', 'markup.deleted punctuation.definition.deleted'], settings: { name: 'Diff deleted', foreground: t.keyword } },
      { scope: ['markup.changed', 'markup.changed punctuation.definition.changed'], settings: { name: 'Diff changed', foreground: t.heading } },
      { scope: ['markup.ignored', 'markup.ignored punctuation.definition.ignored'], settings: { name: 'Diff ignored', foreground: t.operatorMeta } },
      { scope: 'markup.untracked', settings: { name: 'Diff untracked', foreground: t.operatorMeta } },
      { scope: 'markup.quote', settings: { name: 'Markup quote', fontStyle: 'italic' } },

      // ── Meta ──────────────────────────────────────────────
      { scope: ['meta.brace.round', 'meta.brace.square', 'meta.brace.curly', 'meta.delimiter.comma.js', 'meta.function-call.without-arguments.js', 'meta.function-call.method.without-arguments.js'], settings: { name: 'Braces, delimiters', foreground: t.punctuation } },
      { scope: ['meta.function-call.generic.python', 'support.function.builtin.python'], settings: { name: 'Function call (Python)', foreground: t.function } },
      { scope: 'meta.function-call.python meta.function-call.arguments.python', settings: { name: 'Function arguments (Python)', foreground: t.markup } },
      { scope: 'meta.interpolation', settings: { name: 'Interpolation strings', foreground: t.interpolation } },
      { scope: 'meta.instance.constructor', settings: { name: 'Constructor', foreground: t.function } },
      { scope: ['meta.attribute-with-value.class string', 'meta.attribute.class.html string'], settings: { name: 'Class string name', foreground: t.cssClass } },
      { scope: ['meta.attribute-with-value.id string', 'meta.attribute.id.html string'], settings: { name: 'ID string name', foreground: t.cssId } },
      { scope: 'source.json meta.mapping.key string', settings: { name: 'JSON keys', foreground: t.jsonKey } },
      { scope: 'source.yaml meta.mapping.key string', settings: { name: 'YAML keys', foreground: t.yamlKey } },
      { scope: 'meta.object.member', settings: { name: 'Object members', foreground: t.markup } },
      { scope: 'meta.property-list.css variable.other', settings: { name: 'SCSS Variable', foreground: t.scssVar } },
      { scope: ['entity.name.constant.preprocessor', 'meta.preprocessor'], settings: { name: 'Preprocessor', foreground: t.constant } },
      { scope: 'meta.diff.git-diff.header', settings: { name: 'Git diff header', foreground: t.heading } },
      { scope: 'meta.type_params.rust', settings: { name: 'Rust type params', foreground: t.markup } },
      { scope: ['meta.attribute.rust', 'meta.annotation.rust', 'variable.language.rust', 'variable.annotation.rust', 'meta.annotation.rust string', 'meta.annotation.rust keyword', 'meta.annotation.rust keyword.operator', 'meta.attribute.rust string'], settings: { name: 'Rust attributes', foreground: t.commentDoc } },
      { scope: ['meta.type variable', 'meta.type variable.other.readwrite', 'variable.annotation', 'meta.decorator variable.other.readwrite'], settings: { name: 'Type annotation', foreground: t.constant } },

      // ── Punctuation ───────────────────────────────────────
      { scope: 'punctuation', settings: { name: 'Punctuation', foreground: t.punctuation } },
      { scope: ['punctuation.definition.tag', 'punctuation.definition.tag source', 'punctuation.definition.group.begin.ruby', 'punctuation.definition.group.end.ruby', 'punctuation.definition.group.begin.css', 'punctuation.definition.group.end.css', 'punctuation.definition.string.end.html source.css', 'punctuation.definition.block', 'punctuation.definition.parameters.begin', 'punctuation.definition.parameters.end', 'punctuation.separator.parameter', 'punctuation.accessor', 'punctuation.terminator'], settings: { name: 'Punctuation tags', foreground: t.punctuation } },
      { scope: 'punctuation.definition.group', settings: { name: 'Group (regex)', foreground: t.markup } },
      { scope: 'punctuation.definition.comment', settings: { name: 'Comment start / end', foreground: t.punctuationComment } },
      { scope: ['punctuation.definition.variable', 'punctuation.definition.keyword.scss', 'punctuation.definition.entity.css'], settings: { name: 'Variable indicator', foreground: t.punctuationVar } },
      { scope: ['punctuation.section.embedded', 'punctuation.section.embedded entity.name.tag', 'punctuation.section.embedded constant.other', 'punctuation.section.embedded source', 'punctuation.section.embedded.begin'], settings: { name: 'Punctuation section embedded', foreground: t.embedded } },
      { scope: ['punctuation.template-string.element.begin', 'punctuation.template-string.element.end', 'punctuation.definition.string.template.begin', 'punctuation.definition.string.template.end', 'string.quoted.template punctuation.definition.string.begin', 'string.quoted.template punctuation.definition.string.end', 'punctuation.definition.template-expression.begin', 'punctuation.definition.template-expression.end'], settings: { name: 'Punctuation template string', foreground: t.keyword } },
      { scope: ['meta.paragraph.markdown meta.dummy.line-break', 'meta.paragraph.markdown meta.hard-line-break.markdown'], settings: { name: 'Hard line break in Markdown', background: t.constant } },
      { scope: 'markup.underline.link punctuation', settings: { name: 'Punctuation in markdown links', foreground: t.link } },
      { scope: ['meta.brace.round', 'meta.brace.square', 'keyword.operator.type.annotation', 'meta.type storage.modifier.array'], settings: { name: 'Meta braces', foreground: t.punctuation } },

      // ── Regions ───────────────────────────────────────────
      { scope: 'region.redish', settings: { name: 'Region red', foreground: p.red, background: alpha(p.red, '59') } },
      { scope: 'region.orangish', settings: { name: 'Region orange', foreground: p.orange, background: alpha(p.orange, '59') } },
      { scope: 'region.yellowish', settings: { name: 'Region yellow', foreground: p.yellow, background: alpha(p.yellow, '59') } },
      { scope: 'region.greenish', settings: { name: 'Region green', foreground: p.green, background: alpha(p.green, '59') } },
      { scope: 'region.bluish', settings: { name: 'Region blue', foreground: p.cyan, background: alpha(p.cyan, '59') } },
      { scope: 'region.purplish', settings: { name: 'Region purple', foreground: p.purple, background: alpha(p.purple, '59') } },
      { scope: 'region.pinkish', settings: { name: 'Region pink', foreground: p.red, background: alpha(p.red, '59') } },
      { scope: 'region.whitish', settings: { name: 'Region white', foreground: p.white } },

      // ── Source ────────────────────────────────────────────
      { scope: 'source', settings: { name: 'Source', foreground: t.markup } },
      { scope: ['source.scss', 'source.sass'], settings: { name: 'SASS, SCSS default', foreground: t.punctuation } },
      { scope: ['source.sass variable.other', 'source.sass variable.sass', 'source.scss variable.other', 'source.scss variable.scss', 'source.scss variable.sass', 'source.css variable.other', 'source.css variable.scss', 'source.less variable.other', 'source.less variable.other.less', 'source.less variable.declaration.less'], settings: { name: 'SASS, SCSS and LESS variables', fontStyle: 'italic', foreground: t.scssVar } },
      { scope: 'source.git-show.commit.sha', settings: { name: 'Git SHA', foreground: t.gitHash } },
      { scope: ['source.git-show.author', 'source.git-show.date', 'source.git-diff.command', 'source.git-diff.command meta.diff.git-diff.header.from-file', 'source.git-diff.command meta.diff.git-diff.header.to-file'], settings: { name: 'Git metadata', foreground: t.punctuation } },
      { scope: ['source.git-show meta.diff.git-diff.header.extended.index.from-sha', 'source.git-show meta.diff.git-diff.header.extended.index.to-sha'], settings: { name: 'Git diff header hash', foreground: t.gitHash } },
      { scope: 'source.git-show meta.diff.range.unified', settings: { name: 'Git diff header range', foreground: t.diffRange } },
      { scope: ['source.git-show meta.diff.header.from-file', 'source.git-show meta.diff.header.to-file'], settings: { name: 'Git diff header files', foreground: t.punctuation } },

      // ── Storage ───────────────────────────────────────────
      { scope: 'storage', settings: { name: 'Storage', foreground: t.storage } },
      { scope: 'storage.type', settings: { name: 'Storage type', fontStyle: 'italic', foreground: t.storageType } },
      { scope: 'storage.type.extends', settings: { name: 'Extends', fontStyle: 'normal', foreground: t.storage } },
      { scope: 'storage.type.function.arrow', settings: { name: 'Fat arrow function', fontStyle: 'normal', foreground: t.storage } },
      { scope: ['storage.modifier', 'storage.type.modifier'], settings: { name: 'Storage modifier', fontStyle: 'italic', foreground: t.storage } },
      { scope: 'storage.class.restructuredtext.ref', settings: { name: 'RestructuredText refs', foreground: t.constant } },
      { scope: ['storage.modifier.visibility.rust', 'storage.modifier.lifetime.rust'], settings: { name: 'Rust visibility', foreground: t.keyword } },
      { scope: ['storage.modifier.const.rust', 'storage.modifier.dyn.rust', 'storage.modifier.mut.rust', 'storage.modifier.static.rust', 'storage.type.rust', 'storage.type.core.rust', 'storage.class.std.rust'], settings: { name: 'Rust storage types', foreground: t.storageType } },
      { scope: ['storage.type.rust', 'storage.modifier.const.rust', 'storage.modifier.dyn.rust', 'storage.modifier.mut.rust', 'storage.modifier.static.rust', 'keyword.other.rust', 'keyword.other.where.rust'], settings: { name: 'Rust storage (adjusted)', foreground: t.keyword } },
      { scope: 'storage.modifier.import.java', settings: { name: 'Imported Java libraries', foreground: t.markup } },

      // ── Strings ───────────────────────────────────────────
      { scope: 'string', settings: { name: 'String', foreground: t.string } },
      { scope: 'string.unquoted.label', settings: { name: 'String label', foreground: t.markup } },
      { scope: 'string source', settings: { name: 'Source in template string', foreground: t.markup } },
      { scope: ['string source punctuation.section.embedded', 'string punctuation.definition.string source'], settings: { name: 'Embedded punctuation in template string', foreground: t.punctuation } },
      { scope: ['string.other.link.title', 'string.other.link.description'], settings: { name: 'Link title', foreground: t.linkTitle } },
      { scope: 'string.other.link.description.title', settings: { name: 'Link description', foreground: t.linkDesc } },
      { scope: ['string.regexp punctuation.definition.string.begin', 'string.regexp punctuation.definition.string.end'], settings: { name: 'String regexp begin / end', foreground: t.keyword } },
      { scope: ['string.other.ref', 'string.other.restructuredtext.ref'], settings: { name: 'RestructuredText refs', foreground: t.link } },
      { scope: 'string.other.git-status.help.key', settings: { name: 'Git status help key', foreground: t.commentDoc } },
      { scope: 'string.other.git-status.remote', settings: { name: 'Git status remote', foreground: t.gitRemote } },

      // ── Support ───────────────────────────────────────────
      { scope: 'support.constant', settings: { name: 'Library constant', foreground: t.class } },
      { scope: 'support.constant.handlebars', settings: { name: 'Handlebars start / end', foreground: t.punctuation } },
      { scope: 'support.type.vendor-prefix.css', settings: { name: 'Vendor prefix', foreground: t.commentDoc } },
      { scope: 'support.function', settings: { name: 'Support function', foreground: t.function } },
      { scope: 'support.macro', settings: { name: 'Support macro', foreground: t.function } },
      { scope: 'support.function.delimiter.elm', settings: { name: 'Elm function brackets', foreground: t.punctuation } },
      { scope: ['support.type', 'entity.name.type.object.console'], settings: { name: 'Library type', fontStyle: 'italic', foreground: t.type } },
      { scope: ['support.variable', 'support.variable.property'], settings: { name: 'Support variables', foreground: t.class } },
      { scope: 'support.type.property-name', settings: { name: 'Library type property / JSON keys', fontStyle: 'normal', foreground: t.markup } },
      { scope: 'support.class', settings: { name: 'Library class', foreground: t.class } },
      { scope: 'support.constant.core.rust', settings: { name: 'Rust support constant', foreground: t.constant } },
      { scope: ['comment support', 'comment support.class'], settings: { name: 'Comment support', foreground: t.comment } },

      // ── Text ──────────────────────────────────────────────
      { scope: 'text', settings: { name: 'Text', foreground: t.markup } },
      { scope: 'text.find-in-files', settings: { name: 'Search result', foreground: t.markup } },

      // ── Variables ─────────────────────────────────────────
      { scope: ['variable', 'variable.other'], settings: { name: 'Variable', foreground: t.variable } },
      { scope: ['variable.parameter', 'parameters variable.function'], settings: { name: 'Function arguments', fontStyle: 'italic', foreground: t.variableParam } },
      { scope: ['variable.language', 'variable.parameter.function.language.special.self.python', 'variable.parameter.function.language.special.cls.python'], settings: { name: 'Language variables (this, self, super)', fontStyle: 'italic', foreground: t.variableLang } },
      { scope: 'variable.language.arguments', settings: { name: 'Arguments variable', foreground: t.constant } },
      { scope: 'variable.other.class', settings: { name: 'Library function', foreground: t.class } },
      { scope: 'variable.other.constant', settings: { name: 'Immutable variables', foreground: t.constant } },
      { scope: 'variable.other.readwrite', settings: { name: 'Read/write variables', foreground: t.variable } },
      { scope: 'variable.other.member', settings: { name: 'Member variables', foreground: t.variable } },
      { scope: 'variable.other.enummember', settings: { name: 'Enum member', foreground: t.constant } },
      { scope: ['variable.other.property', 'variable.other.property.static', 'variable.other.event'], settings: { name: 'Variable property', foreground: t.variable } },
      { scope: 'variable.function', settings: { name: 'Variable function', foreground: t.function } },
      { scope: 'variable.other.substitution', settings: { name: 'Substitution', foreground: t.variableParam } },
      { scope: ['source.ruby variable.other.readwrite.instance.ruby', 'source.ruby variable.other.readwrite.class.ruby'], settings: { name: 'Ruby instance variables', foreground: t.constant } },
      { scope: 'source.jinja2 variable.other.jinja2.block', settings: { name: 'Jinja2 variable block', foreground: t.function } },
      { scope: 'source.jinja2 variable.other.jinja2', settings: { name: 'Jinja2 variable', foreground: t.variableParam } },
    ],
  };
}

module.exports = buildTheme;
