// ── Token Semantic Map ──────────────────────────────────────
// Maps syntax roles to palette keys for tokenColors.

function tokenMap(p) {
  return {
    comment: p.fgDim,
    commentDoc: p.fgSoft,
    keyword: p.red,
    operator: p.red,
    operatorMeta: p.fgMuted,
    storage: p.red,
    storageType: p.cyan,
    function: p.green,
    string: p.yellow,
    number: p.purple,
    constant: p.purple,
    constantOther: p.fg,
    class: p.cyan,
    tag: p.red,
    attribute: p.cyan,
    variable: p.fg,
    variableParam: p.orange,
    variableLang: p.fgSoft,
    type: p.cyan,
    label: p.purple,
    link: p.green,
    linkTitle: p.red,
    linkDesc: p.cyan,
    heading: p.yellow,
    invalid: p.red,
    invalidDeprecated: p.orange,
    embedded: p.orange,
    interpolation: p.orange,
    punctuation: p.fgMuted,
    punctuationComment: p.fgDim,
    punctuationVar: p.fgSoft,
    markup: p.fg,
    markupRaw: p.orange,
    cssClass: p.green,
    cssId: p.orange,
    cssPseudo: p.cyan,
    scssVar: p.orange,
    jsonKey: p.fg,
    yamlKey: p.red,
    gitRemote: p.red,
    gitLocal: p.cyan,
    gitHead: p.fg,
    gitHash: p.purple,
    diffRange: p.orange,
    region: p.fg,
  };
}

module.exports = tokenMap;
