// ── Token Semantic Map ──────────────────────────────────────
// Maps syntax roles to palette keys for tokenColors.

function tokenMap(p) {
  return {
    comment: p.primaryDim,
    commentDoc: p.primary,
    keyword: p.red,
    operator: p.red,
    operatorMeta: p.primaryMid,
    storage: p.red,
    storageType: p.secondaryDim,
    function: p.secondary,
    string: p.secondaryBright,
    number: p.secondaryDim,
    constant: p.secondaryDim,
    constantOther: p.primaryBright,
    class: p.primaryMid,
    tag: p.red,
    attribute: p.secondary,
    variable: p.primaryBright,
    variableParam: p.secondaryBright,
    variableLang: p.primary,
    type: p.primaryMid,
    label: p.secondaryDim,
    link: p.secondary,
    linkTitle: p.red,
    linkDesc: p.primaryMid,
    heading: p.secondaryBright,
    invalid: p.red,
    invalidDeprecated: p.redBright,
    embedded: p.secondaryBright,
    interpolation: p.secondaryBright,
    punctuation: p.primaryMid,
    punctuationComment: p.primaryDim,
    punctuationVar: p.primary,
    markup: p.primaryBright,
    markupRaw: p.secondaryBright,
    cssClass: p.secondary,
    cssId: p.secondaryBright,
    cssPseudo: p.primaryMid,
    scssVar: p.secondaryBright,
    jsonKey: p.primaryBright,
    yamlKey: p.red,
    gitRemote: p.red,
    gitLocal: p.primaryMid,
    gitHead: p.primaryBright,
    gitHash: p.secondaryDim,
    diffRange: p.secondaryBright,
    region: p.primaryBright,
  };
}

module.exports = tokenMap;
